---
title: "Untitled"
output: html_document
date: "2022-12-15"
---

```{r message=FALSE}
library(tidyverse)
library(data.table)
library(gridExtra)
library(pcalg)
library(GeneNet)
library(bc3net)
library(GENIE3)
#library(testit)
```

# X I. Basic functions
```{r}
### Read in true GRN file from SERGIO ###
#########################################

read_grn <- function(interaction_file, n_genes) {
  
  grn_txt <- read.delim(interaction_file, header=FALSE)
  # 'input_file_taregts' file containing GRN structure and its parameters. for legend, cfr. https://github.com/PayamDiba/SERGIO
  
  
  ### Extracting edges from interaction file ###
  
  grn_edges <- data.frame(matrix(ncol=2,nrow=0, dimnames=list(NULL, c("reg", "target"))))
  count <- 0 
  #count number of regulators in GRN as affirmation that number of edges is correct
  
  for (i in seq(grn_txt[,1])) {
    #iterate over each target gene in the GRN
    gene_row <- as.integer(unlist(strsplit(grn_txt[i,], ','))) 
    #extract info of target gene i
    n_regs <- gene_row[2]
    count <- count + gene_row[2]
    
    for (j in seq(n_regs)) {  
      # iterate over each regulator of the target gene,
      # adding both to the final dataframe as an edge
      df <- data.frame(gene_row[2 + j] + 1, gene_row[1] + 1)
      # '+ 1' to adjust for the 0-index naming of the genes
      grn_edges <- rbind(grn_edges, setNames(df, names(grn_edges)))
    }
  }
  control1 <- count == nrow(grn_edges)
  #control whether all edges have been added to the data frame
  
  ### Control for cyclic edges, which should not be present.
  cyclic <- 0
  for (i in seq(nrow(grn_edges))) {
    edge_to_find <- data.frame(reg=grn_edges[[i, 2]], target=grn_edges[[i, 1]])
    if (nrow(merge(edge_to_find, grn_edges)) > 0) {
      count <- count + 1
    }
  }
  control2 <- cyclic == 0
  
  ### Control for presence of n genes in the GRN
  both <- list()
  for (i in grn_edges["reg"]) {both <- append(both, i)}
  for (i in grn_edges["target"]) {both <- append(both, i)}
  
  control3 <- length(unique(both)) == n_genes
  
  cat('all edges extracted:', control1, '\n') 
  cat('no cyclic edges:', control2, '\n')
  cat(sprintf('%s genes present in GRN:', n_genes), control3)
  
  grn_edges <- as_tibble(grn_edges) %>%
    mutate(reg = as.character(reg), target = as.character(target))
  return(as_tibble(grn_edges))
}


### Reading folder of R objects ###
###################################

### load folder of RData ###
load_rdata <- function(folder) {
  filenames <- dir(folder)
  for (i in filenames) {
    load(sprintf('%s/%s', folder, i), envir=.GlobalEnv)
  }
}

### load folder of rds objects ###
load_rds <- function(folder) {
  
  filenames <- dir(folder)
  for (i in filenames) {
    results <- str_replace(i, ".rds", "")
    sub <- readRDS(sprintf('%s/%s', folder, i))
    assign(results, sub)
  }
}

### inference results to GRN ###
################################

### PC result to GRN
pc_to_grn <- function(inf_out) {
  
  grn <- tribble(~reg, ~target, ~p, ~directed)
  p_vals <- inf_out@pMax
  adj <- summary(inf_out)
  
  for (i in 1:nrow(adj)) {
    targets_of_i <- which(adj[i,-(1:i)] == 1) + i # + 1 to offset the lowered indices because of subsetting
    regs_of_i <- which(adj[-(1:i),i] == 1) + i
    sect <- intersect(targets_of_i, regs_of_i)
    
    if (length(sect) > 0) {
      targets_of_i <- targets_of_i[!(targets_of_i %in% sect)]
      regs_of_i <- regs_of_i[!(regs_of_i %in% sect)]
    }
    
    for (target in targets_of_i) {
      grn <- add_row(grn, reg=i, target=target, p=p_vals[i, target], directed=TRUE)
    }
    for (reg in regs_of_i) {
      grn <- add_row(grn, reg=reg, target=i, p=p_vals[reg, i], directed=TRUE)
    }
    for (node in sect) {
      grn <- add_row(grn, reg=i, target=node, p=p_vals[i, node], directed=FALSE)
    }
  }
  grn <- mutate(grn, method='pc', reg = as.character(reg), target = as.character(target))
  return(grn)
}

### bc3 result to GRN
bc3_to_grn <- function(inf_out) {
  
  grn <- as_edgelist(inf_out)
  
  if (length(grn) > 0) {
    grn <- as_tibble(grn) %>%
    mutate(weight=E(inf_out)$weight, directed=FALSE, method='bc3') %>%
    arrange(desc(weight)) %>%
    rename(reg = V1, target = V2)
    return(grn)
  } else {
    return(NA)
  }
}

### gn result to GRN
gn_to_grn <- function(inf_out) {
  
  if (nrow(inf_out) == 0) {
    return(NA)
  }
  
  grn <- as_tibble(inf_out) %>%
    dplyr::select(node1, node2, pval) %>%
    rename(reg = node1, target = node2) %>% #does genenet return directed edges? Not by default!
    mutate(directed = FALSE, method='gn', reg = as.character(reg), target = as.character(target))
  
  return(grn)
}

### genie result to GRN: only keeping the highest weight edge of both options.
genie_to_grn <- function(inf_out, size=FALSE) {
  if (size) {
    inf_out <- inf_out[1:size,]
  }
  grn <- inf_out %>%
    mutate(edge_key = case_when(reg < target ~paste(reg, target, sep='_'),
                                reg > target ~paste(target, reg, sep='_'))) %>%
    arrange(edge_key) %>%
    distinct(edge_key, .keep_all=TRUE) %>%
    dplyr::select(reg, target, weight) %>%
    arrange(desc(weight))%>%
    mutate(directed = TRUE, method='genie', reg=as.character(reg), target=as.character(target))
  
  return(grn)
}
    
### inference results to GRNs ###
inf_to_grns <- function(inf_results, size=FALSE) {
  
  results_class <- class(inf_results[[1]])
  if (length(results_class) > 1) {
    results_class <- results_class[1]
  }
                          
  n_sims <- length(inf_results)
  grn_list <- vector("list", n_sims)
  
  ### PC
  if (results_class == 'pcAlgo') {
    print('PC')
    for (i in 1:n_sims) {
      grn_list[[i]] <- pc_to_grn(inf_results[[i]])
      if (i %in% seq(0, n_sims, 10)) {
        print(paste(i, "% has been processed"))
      }
    }
  }
  ### bc3
  else if (results_class == 'igraph') {
    print('bc3')
    for (i in 1:n_sims) {
      grn_list[[i]] <- bc3_to_grn(inf_results[[i]])
      if (i %in% seq(0, n_sims, 10)) {
        print(paste(i, "% has been processed"))
      }
    }
  }
  ### genenet
  else if (results_class == 'data.frame') {
    print('genenet')
    for (i in 1:n_sims) {
      grn_list[[i]] <- gn_to_grn(inf_results[[i]])
      if (i %in% seq(0, n_sims, 10)) {
        print(paste(i, "% has been processed"))
      }
    }
  }
  ### Genie : delete directed edges with lowest weight
  else if (is(inf_results[[1]], "tbl_df")) {
    print('genie')
    for (i in 1:n_sims) {
      grn_list[[i]] <- genie_to_grn(inf_results[[i]], size=size)
      if (i %in% seq(0, n_sims, 10)) {
        print(paste(i, "% has been processed"))
      }
    }
  }
  else {
    print('No valid object class')
  }
  return(grn_list)
}

### Summarizing statistics of interest per list of GRNs ###
##################################################

### Precision and recall ###

summarise_grn <- function(fake_grn, true_grn, true_grn_inverse=FALSE) {
  
  if (is(true_grn_inverse, 'logical')) {
    true_grn_inverse <- mutate(true_grn, reg2 = target, target2 = reg) %>%
      select(reg2, target2) %>%
      rename(reg=reg2, target=target2)
  }
  
  if (is(fake_grn, 'logical')) {
    
    stats <- tribble(~prec, ~rec, ~TP, ~PP, 0, 0, 0, 0)
    
  } else {
    
    TP <- nrow(inner_join(fake_grn, true_grn)) + nrow(inner_join(fake_grn, true_grn_inverse))
    PP <- nrow(fake_grn) # Proposed positives = TP + FP
    prec <- TP / PP
    rec <- TP / nrow(true_grn) # nrow(true_grn) = TP + FN (all positives)
    
    stats <- tribble(~prec, ~rec, ~TP, ~PP, prec, rec, TP, PP)
  }
  
  return(stats) 
  
}

### list of GRNs to statistics ###

grns_to_stats <- function(grn_list, true_grn) {
  
  stats <- tribble(~precision, ~recall, ~TP, ~PP)
  true_grn_inverse <- mutate(true_grn, reg2 = target, target2 = reg) %>%
    select(reg2, target2) %>%
    rename(reg=reg2, target=target2)
  
  if (is(grn_list[[1]], 'logical')) {
    i <- 2
    method <- NA
    while(is.na(method) & i <= length(grn_list)) {
      if (is(grn_list[[i]], 'logical')) {
        i <- i + 1
      } else {
        method <- grn_list[[i]]$method[1]
      }
    }
    if (i > length(grn_list)) {
      print('No results found')
      return(NA)
    }
  } else {
    method <- grn_list[[1]]$method[1]
  }
  
  
  for (i in 1:length(grn_list)) {
    
    fake_grn <- grn_list[[i]]
    stats <- rbind(stats, summarise_grn(fake_grn, true_grn, true_grn_inverse=true_grn_inverse))
    
    cat(sprintf('%s/%s\r', i, length(grn_list)))
  }
  
  stats <- mutate(stats, method = method)
  return(stats)
}


### ranked precision of list of GRNs ###
########################################
grns_to_rankprec <- function(grn_list, true_grn) {
  grn_rank <- tribble(~reg, ~target, ~weight, ~directed, ~method, ~rank)
  ### add rank and concatenate all grns
  for (i in 1:length(grn_list)) {
    if (!(is(grn_list[[i]], 'logical'))) {
      grn_list[[i]] <- mutate(grn_list[[i]], rank = 1:nrow(grn_list[[i]]))
      grn_rank <- rbind(grn_rank, grn_list[[i]])
    }
  }
  grn_rank <- arrange(grn_rank, rank)
  
  ### add 1 for TP 0 for FP
  true_regs <- true_grn$reg; fake_regs <- grn_rank$reg
  true_targets <- true_grn$target; fake_targets <- grn_rank$target
  TPs <- c()
  for (i in 1:nrow(true_grn)) {
    curr_reg <- true_regs[i]
    curr_target <- true_targets[i]
    TPs <- c(TPs, which(fake_regs == curr_reg & fake_targets == curr_target))
    TPs <- c(TPs, which(fake_regs == curr_target & fake_targets == curr_reg))
  }
  
  grn_rank <- mutate(grn_rank, TP = 0)
  for (i in TPs) {
    grn_rank[i, 'TP'] = 1
  }
  grn_rankprec <- group_by(grn_rank, rank) %>%
    summarise(rank_precision=sum(TP)/100, rank_precision_adj=sum(TP)/(sum(rank) / mean(rank)), count = sum(rank) / mean(rank))
  
  return(list(grn_rank, grn_rankprec))
}

### Plotting ###
plot_rankprec <- function(m1, m2, m3, m4, exp_precision) {
  
  ### Ranked Precision
  plot1 <- ggplot(m1[[2]], aes(x=rank, y=rank_precision)) +
    geom_smooth() +
    ggtitle("PC") +
    xlab("Rank") + ylab("Ranked Precision") +
    geom_hline(yintercept=exp_precision, linetype="dashed", color="red")
  plot2 <- ggplot(m2[[2]], aes(x=rank, y=rank_precision)) +
    geom_smooth() +
    ggtitle("bc3net") +
    xlab("Rank") + ylab("Ranked Precision") +
    geom_hline(yintercept=exp_precision, linetype="dashed", color="red")
  plot3 <- ggplot(m3[[2]], aes(x=rank, y=rank_precision)) +
    geom_smooth() +
    ggtitle("GeneNet") +
    xlab("Rank") + ylab("Ranked Precision") +
    geom_hline(yintercept=exp_precision, linetype="dashed", color="red")
  plot4 <- ggplot(m4[[2]], aes(x=rank, y=rank_precision)) +
    geom_smooth() +
    ggtitle("GENIE3") +
    xlab("Rank") + ylab("Ranked Precision") +
    geom_hline(yintercept=exp_precision, linetype="dashed", color="red") 
  # note that earlier ranks have more values which might confound results. This is definitely true for bc3
  
  ### Adjusted ranked precision
  plot5 <- ggplot(m1[[2]], aes(x=rank, y=rank_precision_adj)) +
    geom_smooth() +
    ggtitle("PC") +
    xlab("Rank") + ylab("Ranked Precision (adjusted)") +
    geom_hline(yintercept=exp_precision, linetype="dashed", color="red")
  plot6 <- ggplot(m2[[2]], aes(x=rank, y=rank_precision_adj)) +
    geom_smooth() +
    ggtitle("bc3net") +
    xlab("Rank") + ylab("Ranked Precision (adjusted)") +
    geom_hline(yintercept=exp_precision, linetype="dashed", color="red")
  plot7 <- ggplot(m3[[2]], aes(x=rank, y=rank_precision_adj)) +
    geom_smooth() +
    ggtitle("GeneNet") +
    xlab("Rank") + ylab("Ranked Precision (adjusted)") +
    geom_hline(yintercept=exp_precision, linetype="dashed", color="red")
  plot8 <- ggplot(m4[[2]], aes(x=rank, y=rank_precision_adj)) +
    geom_smooth() +
    ggtitle("GENIE3") +
    xlab("Rank") + ylab("Ranked Precision (adjusted)") +
    geom_hline(yintercept=exp_precision, linetype="dashed", color="red") 
  
  grid.arrange(plot1, plot2, plot3, plot4, plot5, plot6, plot7, plot8, ncol=4)
}

calc_auc <- function(tib) {
  rec <- tib$cumrec
  prec <- tib$cumprec
  
  total <- 0
  for (i in 2:length(rec)) {
    
    curr_rec <- rec[i]; curr_prec <- prec[i]
    last_rec <- rec[i-1]; last_prec <- prec[i-1]
    
    x_diff = curr_rec - last_rec
    y_avg = (curr_prec + last_prec) / 2
    
    integral_iter <- x_diff * y_avg
    total <- total + integral_iter
  }
  return(total)
}

calc_sign <- function(tib, grn, pc=FALSE, val="score") {
  tib <- tib[[2]][[1]] %>%
    filter(directed==TRUE, TP == 1)
  grn <- mutate(grn, sign = TRUE)
  tib <- left_join(tib, grn, by = c("reg", "target"))
  
  if (pc == TRUE) {
    tib <- mutate(tib, sign = ifelse(is.na(sign), 1, 0))
  } else {
    tib <- mutate(tib, sign = ifelse(is.na(sign), 0, 1))
  }
  
  if (val == "score") {
    return(sum(tib$sign) / nrow(tib))
  } else if (val == "tibble") {
    return(tib)
  }
}
```


# LOAD DATA

```{r}
true_grn1 <- read_grn('SERGIO/data_sets/De-noised_100G_9T_300cPerT_4_DS1/Interaction_cID_4.txt', 100)
true_grn4 <- read_grn('SERGIO/data_sets/De-noised_400G_9T_300cPerT_5_DS2/Interaction_cID_5.txt', 400)
true_grn12 <- read_grn('SERGIO/data_sets/De-noised_1200G_9T_300cPerT_6_DS3/Interaction_cID_6.txt', 1200)

exp_precision1 <- nrow(true_grn1) / ((100*100 - 100) / 2)
exp_precision4 <- nrow(true_grn4) / ((400*400 - 400) / 2)
exp_precision12 <- nrow(true_grn12) / ((1200*1200 - 1200) / 2)
```
## clean
### 100g

```{r}
c1g0_pc_stats <- readRDS('stat_objects/100g/60c/c1g0_pc_stats.rds')
c1g0_bc3_stats <- readRDS('stat_objects/100g/60c/c1g0_bc3_stats.rds')
c1g0_gn_stats <- readRDS('stat_objects/100g/60c/c1g0_gn_stats.rds')
c1g0_genie_stats <- readRDS('stat_objects/100g/60c/c1g0_genie_stats.rds')

c1g2_pc_stats <- readRDS('stat_objects/100g/200c/c1g2_pc_stats.rds')
c1g2_bc3_stats <- readRDS('stat_objects/100g/200c/c1g2_bc3_stats.rds')
c1g2_gn_stats <- readRDS('stat_objects/100g/200c/c1g2_gn_stats.rds')
c1g2_genie_stats <- readRDS('stat_objects/100g/200c/c1g2_genie_stats.rds')

c1g5_pc_stats <- readRDS('stat_objects/100g/500c/c1g5_pc_stats.rds')
c1g5_bc3_stats <- readRDS('stat_objects/100g/500c/c1g5_bc3_stats.rds')
c1g5_gn_stats <- readRDS('stat_objects/100g/500c/c1g5_gn_stats.rds')
c1g5_genie_stats <- readRDS('stat_objects/100g/500c/c1g5_genie_stats.rds')

c1g10_pc_stats <- readRDS('stat_objects/100g/1000c/c1g10_pc_stats.rds')
c1g10_bc3_stats <- readRDS('stat_objects/100g/1000c/c1g10_bc3_stats.rds')
c1g10_gn_stats <- readRDS('stat_objects/100g/1000c/c1g10_gn_stats.rds')
c1g10_genie_stats <- readRDS('stat_objects/100g/1000c/c1g10_genie_stats.rds')
```

### 400g

```{r}
c4g0_pc_stats <- readRDS('stat_objects/400g/60c/c4g0_pc_stats.rds')
c4g0_bc3_stats <- readRDS('stat_objects/400g/60c/c4g0_bc3_stats.rds')
c4g0_gn_stats <- readRDS('stat_objects/400g/60c/c4g0_gn_stats.rds')
c4g0_genie_stats <- readRDS('stat_objects/400g/60c/c4g0_genie_stats.rds')

c4g2_pc_stats <- readRDS('stat_objects/400g/200c/c4g2_pc_stats.rds')
c4g2_bc3_stats <- readRDS('stat_objects/400g/200c/c4g2_bc3_stats.rds')
c4g2_gn_stats <- readRDS('stat_objects/400g/200c/c4g2_gn_stats.rds')
c4g2_genie_stats <- readRDS('stat_objects/400g/200c/c4g2_genie_stats.rds')

c4g5_pc_stats <- readRDS('stat_objects/400g/500c/c4g5_pc_stats.rds')
c4g5_bc3_stats <- readRDS('stat_objects/400g/500c/c4g5_bc3_stats.rds')
c4g5_gn_stats <- readRDS('stat_objects/400g/500c/c4g5_gn_stats.rds')
c4g5_genie_stats <- readRDS('stat_objects/400g/500c/c4g5_genie_stats.rds')

c4g10_pc_stats <- readRDS('stat_objects/400g/1000c/c4g10_pc_stats.rds')
c4g10_bc3_stats <- readRDS('stat_objects/400g/1000c/c4g10_bc3_stats.rds')
c4g10_gn_stats <- readRDS('stat_objects/400g/1000c/c4g10_gn_stats.rds')
c4g10_genie_stats <- readRDS('stat_objects/400g/1000c/c4g10_genie_stats.rds')
```

### 1200g

```{r}
c12g0_pc_stats <- readRDS('stat_objects/1200g/60c/c12g0_pc_stats.rds')
c12g0_bc3_stats <- readRDS('stat_objects/1200g/60c/c12g0_bc3_stats.rds')
c12g0_gn_stats <- readRDS('stat_objects/1200g/60c/c12g0_gn_stats.rds')
c12g0_genie_stats <- readRDS('stat_objects/1200g/60c/c12g0_genie_stats.rds')

c12g2_pc_stats <- readRDS('stat_objects/1200g/200c/c12g2_pc_stats.rds')
c12g2_bc3_stats <- readRDS('stat_objects/1200g/200c/c12g2_bc3_stats.rds')
c12g2_gn_stats <- readRDS('stat_objects/1200g/200c/c12g2_gn_stats.rds')
c12g2_genie_stats <- readRDS('stat_objects/1200g/200c/c12g2_genie_stats.rds')

c12g5_pc_stats <- readRDS('stat_objects/1200g/500c/c12g5_pc_stats.rds')
c12g5_bc3_stats <- readRDS('stat_objects/1200g/500c/c12g5_bc3_stats.rds')
c12g5_gn_stats <- readRDS('stat_objects/1200g/500c/c12g5_gn_stats.rds')
c12g5_genie_stats <- readRDS('stat_objects/1200g/500c/c12g5_genie_stats.rds')

#c12g10_pc_stats <- readRDS('stat_objects/1200g/1000c/c12g10_pc_stats.rds')
c12g10_bc3_stats <- readRDS('stat_objects/1200g/1000c/c12g10_bc3_stats.rds')
c12g10_gn_stats <- readRDS('stat_objects/1200g/1000c/c12g10_gn_stats.rds')
c12g10_genie_stats <- readRDS('stat_objects/1200g/1000c/c12g10_genie_stats.rds')
```

## dirty
### 100g


```{r}
d1g0_pc_stats <- readRDS('stat_objects/100g/60c/d1g0_pc_stats.rds')
d1g0_bc3_stats <- readRDS('stat_objects/100g/60c/d1g0_bc3_stats.rds')
d1g0_gn_stats <- readRDS('stat_objects/100g/60c/d1g0_gn_stats.rds')
d1g0_genie_stats <- readRDS('stat_objects/100g/60c/d1g0_genie_stats.rds')

d1g2_pc_stats <- readRDS('stat_objects/100g/200c/d1g2_pc_stats.rds')
d1g2_bc3_stats <- readRDS('stat_objects/100g/200c/d1g2_bc3_stats.rds')
d1g2_gn_stats <- readRDS('stat_objects/100g/200c/d1g2_gn_stats.rds')
d1g2_genie_stats <- readRDS('stat_objects/100g/200c/d1g2_genie_stats.rds')

d1g5_pc_stats <- readRDS('stat_objects/100g/500c/d1g5_pc_stats.rds')
d1g5_bc3_stats <- readRDS('stat_objects/100g/500c/d1g5_bc3_stats.rds')
d1g5_gn_stats <- readRDS('stat_objects/100g/500c/d1g5_gn_stats.rds')
d1g5_genie_stats <- readRDS('stat_objects/100g/500c/d1g5_genie_stats.rds')

d1g10_pc_stats <- readRDS('stat_objects/100g/1000c/d1g10_pc_stats.rds')
d1g10_bc3_stats <- readRDS('stat_objects/100g/1000c/d1g10_bc3_stats.rds')
d1g10_gn_stats <- readRDS('stat_objects/100g/1000c/d1g10_gn_stats.rds')
d1g10_genie_stats <- readRDS('stat_objects/100g/1000c/d1g10_genie_stats.rds')
```

### 400g

```{r}
d4g0_pc_stats <- readRDS('stat_objects/400g/60c/d4g0_pc_stats.rds')
d4g0_bc3_stats <- readRDS('stat_objects/400g/60c/d4g0_bc3_stats.rds')
d4g0_gn_stats <- readRDS('stat_objects/400g/60c/d4g0_gn_stats.rds')
d4g0_genie_stats <- readRDS('stat_objects/400g/60c/d4g0_genie_stats.rds')

d4g2_pc_stats <- readRDS('stat_objects/400g/200c/d4g2_pc_stats.rds')
d4g2_bc3_stats <- readRDS('stat_objects/400g/200c/d4g2_bc3_stats.rds')
d4g2_gn_stats <- readRDS('stat_objects/400g/200c/d4g2_gn_stats.rds')
d4g2_genie_stats <- readRDS('stat_objects/400g/200c/d4g2_genie_stats.rds')

d4g5_pc_stats <- readRDS('stat_objects/400g/500c/d4g5_pc_stats.rds')
d4g5_bc3_stats <- readRDS('stat_objects/400g/500c/d4g5_bc3_stats.rds')
d4g5_gn_stats <- readRDS('stat_objects/400g/500c/d4g5_gn_stats.rds')
d4g5_genie_stats <- readRDS('stat_objects/400g/500c/d4g5_genie_stats.rds')

d4g10_pc_stats <- readRDS('stat_objects/400g/1000c/d4g10_pc_stats.rds')
d4g10_bc3_stats <- readRDS('stat_objects/400g/1000c/d4g10_bc3_stats.rds')
d4g10_gn_stats <- readRDS('stat_objects/400g/1000c/d4g10_gn_stats.rds')
d4g10_genie_stats <- readRDS('stat_objects/400g/1000c/d4g10_genie_stats.rds')
```

### 1200g

```{r}
d12g0_pc_stats <- readRDS('stat_objects/1200g/60c/d12g0_pc_stats.rds')
d12g0_bc3_stats <- readRDS('stat_objects/1200g/60c/d12g0_bc3_stats.rds')
d12g0_gn_stats <- readRDS('stat_objects/1200g/60c/d12g0_gn_stats.rds')
d12g0_genie_stats <- readRDS('stat_objects/1200g/60c/d12g0_genie_stats.rds')

d12g2_pc_stats <- readRDS('stat_objects/1200g/200c/d12g2_pc_stats.rds')
d12g2_bc3_stats <- readRDS('stat_objects/1200g/200c/d12g2_bc3_stats.rds')
d12g2_gn_stats <- readRDS('stat_objects/1200g/200c/d12g2_gn_stats.rds')
d12g2_genie_stats <- readRDS('stat_objects/1200g/200c/d12g2_genie_stats.rds')

d12g5_pc_stats <- readRDS('stat_objects/1200g/500c/d12g5_pc_stats.rds')
d12g5_bc3_stats <- readRDS('stat_objects/1200g/500c/d12g5_bc3_stats.rds')
d12g5_gn_stats <- readRDS('stat_objects/1200g/500c/d12g5_gn_stats.rds')
d12g5_genie_stats <- readRDS('stat_objects/1200g/500c/d12g5_genie_stats.rds')

#d12g10_pc_stats <- readRDS('stat_objects/1200g/1000c/d4g10_pc_stats.rds')
d12g10_bc3_stats <- readRDS('stat_objects/1200g/1000c/d12g10_bc3_stats.rds')
d12g10_gn_stats <- readRDS('stat_objects/1200g/1000c/d12g10_gn_stats.rds')
d12g10_genie_stats <- readRDS('stat_objects/1200g/1000c/d12g10_genie_stats.rds')
```

# Plots

## Precision vs Observations

### clean
#### 100g

```{r}
c1g0_pc_stats[[1]] <- c1g0_pc_stats[[1]] %>%
  mutate(Plants = "60")
c1g0_bc3_stats[[1]] <- c1g0_bc3_stats[[1]] %>%
  mutate(Plants = "60")
c1g0_gn_stats[[1]] <- c1g0_gn_stats[[1]] %>%
  mutate(Plants = "60")
c1g0_genie_stats[[1]] <- c1g0_genie_stats[[1]] %>%
  mutate(Plants = "60")

c1g2_pc_stats[[1]] <- c1g2_pc_stats[[1]] %>%
  mutate(Plants = "200")
c1g2_bc3_stats[[1]] <- c1g2_bc3_stats[[1]] %>%
  mutate(Plants = "200")
#c1g2_gn_stats[[1]] <- c1g2_gn_stats[[1]] %>%
  #mutate(Plants = "200")
c1g2_genie_stats[[1]] <- c1g2_genie_stats[[1]] %>%
  mutate(Plants = "200")

c1g5_pc_stats[[1]] <- c1g5_pc_stats[[1]] %>%
  mutate(Plants = "500")
c1g5_bc3_stats[[1]] <- c1g5_bc3_stats[[1]] %>%
  mutate(Plants = "500")
c1g5_gn_stats[[1]] <- c1g5_gn_stats[[1]] %>%
  mutate(Plants = "500")
c1g5_genie_stats[[1]] <- c1g5_genie_stats[[1]] %>%
  mutate(Plants = "500")

c1g10_pc_stats[[1]] <- c1g10_pc_stats[[1]] %>%
  mutate(Plants = "1000")
c1g10_bc3_stats[[1]] <- c1g10_bc3_stats[[1]] %>%
  mutate(Plants = "1000")
c1g10_gn_stats[[1]] <- c1g10_gn_stats[[1]] %>%
  mutate(Plants = "1000")
c1g10_genie_stats[[1]] <- c1g10_genie_stats[[1]] %>%
  mutate(Plants = "1000")
```

```{r}
c1g_pc_merged <- rbind(c1g0_pc_stats[[1]], c1g2_pc_stats[[1]], c1g5_pc_stats[[1]], c1g10_pc_stats[[1]])
c1g_pc_merged$Plants <- factor(c1g_pc_merged$Plants, levels=c("60", "200", "500", "1000"))

c1g_bc3_merged <- rbind(c1g0_bc3_stats[[1]], c1g2_bc3_stats[[1]], c1g5_bc3_stats[[1]], c1g10_bc3_stats[[1]])
c1g_bc3_merged$Plants <- factor(c1g_bc3_merged$Plants, levels=c("60", "200", "500", "1000"))

c1g_gn_merged <- rbind(c1g0_gn_stats[[1]], c1g2_gn_stats[[1]], c1g5_gn_stats[[1]], c1g10_gn_stats[[1]])
c1g_gn_merged$Plants <- factor(c1g_gn_merged$Plants, levels=c("60", "200", "500", "1000"))

c1g_genie_merged <- rbind(c1g0_genie_stats[[1]], c1g2_genie_stats[[1]], c1g5_genie_stats[[1]], c1g10_genie_stats[[1]])
c1g_genie_merged$Plants <- factor(c1g_genie_merged$Plants, levels=c("60", "200", "500", "1000"))


ggplot(c1g_pc_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("PC - 100 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
ggplot(c1g_bc3_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("BC3NET - 100 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
ggplot(c1g_gn_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("GeneNet - 100 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
ggplot(c1g_genie_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("GENIE3 - 100 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
```


#### 400g

```{r}
c4g0_pc_stats[[1]] <- c4g0_pc_stats[[1]] %>%
  mutate(Plants = "60")
c4g0_bc3_stats[[1]] <- c4g0_bc3_stats[[1]] %>%
  mutate(Plants = "60")
c4g0_gn_stats[[1]] <- c4g0_gn_stats[[1]] %>%
  mutate(Plants = "60")
c4g0_genie_stats[[1]] <- c4g0_genie_stats[[1]] %>%
  mutate(Plants = "60")

c4g2_pc_stats[[1]] <- c4g2_pc_stats[[1]] %>%
  mutate(Plants = "200")
c4g2_bc3_stats[[1]] <- c4g2_bc3_stats[[1]] %>%
  mutate(Plants = "200")
c4g2_gn_stats[[1]] <- c4g2_gn_stats[[1]] %>%
  mutate(Plants = "200")
c4g2_genie_stats[[1]] <- c4g2_genie_stats[[1]] %>%
  mutate(Plants = "200")

c4g5_pc_stats[[1]] <- c4g5_pc_stats[[1]] %>%
  mutate(Plants = "500")
c4g5_bc3_stats[[1]] <- c4g5_bc3_stats[[1]] %>%
  mutate(Plants = "500")
#c4g5_gn_stats[[1]] <- c4g5_gn_stats[[1]] %>%
  #mutate(Plants = "500")
c4g5_genie_stats[[1]] <- c4g5_genie_stats[[1]] %>%
  mutate(Plants = "500")

c4g10_pc_stats[[1]] <- c4g10_pc_stats[[1]] %>%
  mutate(Plants = "1000")
c4g10_bc3_stats[[1]] <- c4g10_bc3_stats[[1]] %>%
  mutate(Plants = "1000")
c4g10_gn_stats[[1]] <- c4g10_gn_stats[[1]] %>%
  mutate(Plants = "1000")
c4g10_genie_stats[[1]] <- c4g10_genie_stats[[1]] %>%
  mutate(Plants = "1000")


```

```{r}
c4g_pc_merged <- rbind(c4g0_pc_stats[[1]], c4g2_pc_stats[[1]], c4g5_pc_stats[[1]], c4g10_pc_stats[[1]])
c4g_pc_merged$Plants <- factor(c4g_pc_merged$Plants, levels=c("60", "200", "500", "1000"))

c4g_bc3_merged <- rbind(c4g0_bc3_stats[[1]], c4g2_bc3_stats[[1]], c4g5_bc3_stats[[1]], c4g10_bc3_stats[[1]])
c4g_bc3_merged$Plants <- factor(c4g_bc3_merged$Plants, levels=c("60", "200", "500", "1000"))

c4g_gn_merged <- rbind(c4g0_gn_stats[[1]], c4g2_gn_stats[[1]], c4g10_gn_stats[[1]])
c4g_gn_merged$Plants <- factor(c4g_gn_merged$Plants, levels=c("60", "200", "500", "1000"))

c4g_genie_merged <- rbind(c4g0_genie_stats[[1]], c4g2_genie_stats[[1]], c4g5_genie_stats[[1]], c4g10_genie_stats[[1]])
c4g_genie_merged$Plants <- factor(c4g_genie_merged$Plants, levels=c("60", "200", "500", "1000"))


ggplot(c4g_pc_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("PC - 400 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")
ggplot(c4g_bc3_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("BC3NET - 400 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")
ggplot(c4g_gn_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("GeneNet - 400 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")
ggplot(c4g_genie_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("GENIE3 - 400 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")


```

#### 1200g

```{r}
c12g0_pc_stats[[1]] <- c12g0_pc_stats[[1]] %>%
  mutate(Plants = "60")
c12g0_bc3_stats[[1]] <- c12g0_bc3_stats[[1]] %>%
  mutate(Plants = "60")
c12g0_gn_stats[[1]] <- c12g0_gn_stats[[1]] %>%
  mutate(Plants = "60")
c12g0_genie_stats[[1]] <- c12g0_genie_stats[[1]] %>%
  mutate(Plants = "60")

c12g2_pc_stats[[1]] <- c12g2_pc_stats[[1]] %>%
  mutate(Plants = "200")
c12g2_bc3_stats[[1]] <- c12g2_bc3_stats[[1]] %>%
  mutate(Plants = "200")
c12g2_gn_stats[[1]] <- c12g2_gn_stats[[1]] %>%
  mutate(Plants = "200")
c12g2_genie_stats[[1]] <- c12g2_genie_stats[[1]] %>%
  mutate(Plants = "200")

c12g5_pc_stats[[1]] <- c12g5_pc_stats[[1]] %>%
  mutate(Plants = "500")
c12g5_bc3_stats[[1]] <- c12g5_bc3_stats[[1]] %>%
  mutate(Plants = "500")
c12g5_gn_stats[[1]] <- c12g5_gn_stats[[1]] %>%
  mutate(Plants = "500")
c12g5_genie_stats[[1]] <- c12g5_genie_stats[[1]] %>%
  mutate(Plants = "500")

#c12g10_pc_stats[[1]] <- c12g10_pc_stats[[1]] %>%
  #mutate(Plants = "1000")
c12g10_bc3_stats[[1]] <- c12g10_bc3_stats[[1]] %>%
  mutate(Plants = "1000")
#c12g10_gn_stats[[1]] <- c12g10_gn_stats[[1]] %>%
  #mutate(Plants = "1000")
c12g10_genie_stats[[1]] <- c12g10_genie_stats[[1]] %>%
  mutate(Plants = "1000")
```

```{r}
c12g_pc_merged <- rbind(c12g0_pc_stats[[1]], c12g2_pc_stats[[1]], c12g5_pc_stats[[1]])
c12g_pc_merged$Plants <- factor(c12g_pc_merged$Plants, levels=c("60", "200", "500"))

c12g_bc3_merged <- rbind(c12g0_bc3_stats[[1]], c12g2_bc3_stats[[1]], c12g5_bc3_stats[[1]], c12g10_bc3_stats[[1]])
c12g_bc3_merged$Plants <- factor(c12g_bc3_merged$Plants, levels=c("60", "200", "500", "1000"))

c12g_gn_merged <- rbind(c12g0_gn_stats[[1]], c12g2_gn_stats[[1]], c12g5_gn_stats[[1]])
c12g_gn_merged$Plants <- factor(c12g_gn_merged$Plants, levels=c("60", "200", "500", "1000"))

c12g_genie_merged <- rbind(c12g0_genie_stats[[1]], c12g2_genie_stats[[1]], c12g5_genie_stats[[1]], c12g10_genie_stats[[1]])
c12g_genie_merged$Plants <- factor(c12g_genie_merged$Plants, levels=c("60", "200", "500", "1000"))


ggplot(c12g_pc_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("PC - 1200 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
ggplot(c12g_bc3_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("BC3NET - 1200 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
ggplot(c12g_gn_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("GeneNet - 1200 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
ggplot(c12g_genie_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("GENIE3 - 1200 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")


```

### dirty
#### 100g

```{r}
d1g0_pc_stats[[1]] <- d1g0_pc_stats[[1]] %>%
  mutate(Plants = "60")
d1g0_bc3_stats[[1]] <- d1g0_bc3_stats[[1]] %>%
  mutate(Plants = "60")
d1g0_gn_stats[[1]] <- d1g0_gn_stats[[1]] %>%
  mutate(Plants = "60")
d1g0_genie_stats[[1]] <- d1g0_genie_stats[[1]] %>%
  mutate(Plants = "60")

d1g2_pc_stats[[1]] <- d1g2_pc_stats[[1]] %>%
  mutate(Plants = "200")
d1g2_bc3_stats[[1]] <- d1g2_bc3_stats[[1]] %>%
  mutate(Plants = "200")
d1g2_gn_stats[[1]] <- d1g2_gn_stats[[1]] %>%
  mutate(Plants = "200")
d1g2_genie_stats[[1]] <- d1g2_genie_stats[[1]] %>%
  mutate(Plants = "200")

d1g5_pc_stats[[1]] <- d1g5_pc_stats[[1]] %>%
  mutate(Plants = "500")
d1g5_bc3_stats[[1]] <- d1g5_bc3_stats[[1]] %>%
  mutate(Plants = "500")
d1g5_gn_stats[[1]] <- d1g5_gn_stats[[1]] %>%
  mutate(Plants = "500")
d1g5_genie_stats[[1]] <- d1g5_genie_stats[[1]] %>%
  mutate(Plants = "500")

d1g10_pc_stats[[1]] <- d1g10_pc_stats[[1]] %>%
  mutate(Plants = "1000")
d1g10_bc3_stats[[1]] <- d1g10_bc3_stats[[1]] %>%
  mutate(Plants = "1000")
d1g10_gn_stats[[1]] <- d1g10_gn_stats[[1]] %>%
  mutate(Plants = "1000")
d1g10_genie_stats[[1]] <- d1g10_genie_stats[[1]] %>%
  mutate(Plants = "1000")
```

```{r}
d1g_pc_merged <- rbind(d1g0_pc_stats[[1]], d1g2_pc_stats[[1]], d1g5_pc_stats[[1]], d1g10_pc_stats[[1]])
d1g_pc_merged$Plants <- factor(d1g_pc_merged$Plants, levels=c("60", "200", "500", "1000"))

d1g_bc3_merged <- rbind(d1g0_bc3_stats[[1]], d1g2_bc3_stats[[1]], d1g5_bc3_stats[[1]], d1g10_bc3_stats[[1]])
d1g_bc3_merged$Plants <- factor(d1g_bc3_merged$Plants, levels=c("60", "200", "500", "1000"))

d1g_gn_merged <- rbind(d1g0_gn_stats[[1]], d1g2_gn_stats[[1]], d1g5_gn_stats[[1]], d1g10_gn_stats[[1]])
d1g_gn_merged$Plants <- factor(d1g_gn_merged$Plants, levels=c("60", "200", "500", "1000"))

d1g_genie_merged <- rbind(d1g0_genie_stats[[1]], d1g2_genie_stats[[1]], d1g5_genie_stats[[1]], d1g10_genie_stats[[1]])
d1g_genie_merged$Plants <- factor(d1g_genie_merged$Plants, levels=c("60", "200", "500", "1000"))


ggplot(d1g_pc_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("PC - 100 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
ggplot(d1g_bc3_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("BC3NET - 100 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
ggplot(d1g_gn_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("GeneNet - 100 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
ggplot(d1g_genie_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("GENIE3 - 100 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
```


#### 400g

```{r}
d4g0_pc_stats[[1]] <- d4g0_pc_stats[[1]] %>%
  mutate(Plants = "60")
d4g0_bc3_stats[[1]] <- d4g0_bc3_stats[[1]] %>%
  mutate(Plants = "60")
d4g0_gn_stats[[1]] <- d4g0_gn_stats[[1]] %>%
  mutate(Plants = "60")
d4g0_genie_stats[[1]] <- d4g0_genie_stats[[1]] %>%
  mutate(Plants = "60")

d4g2_pc_stats[[1]] <- d4g2_pc_stats[[1]] %>%
  mutate(Plants = "200")
d4g2_bc3_stats[[1]] <- d4g2_bc3_stats[[1]] %>%
  mutate(Plants = "200")
d4g2_gn_stats[[1]] <- d4g2_gn_stats[[1]] %>%
  mutate(Plants = "200")
d4g2_genie_stats[[1]] <- d4g2_genie_stats[[1]] %>%
  mutate(Plants = "200")

d4g5_pc_stats[[1]] <- d4g5_pc_stats[[1]] %>%
  mutate(Plants = "500")
d4g5_bc3_stats[[1]] <- d4g5_bc3_stats[[1]] %>%
  mutate(Plants = "500")
d4g5_gn_stats[[1]] <- d4g5_gn_stats[[1]] %>%
  mutate(Plants = "500")
d4g5_genie_stats[[1]] <- d4g5_genie_stats[[1]] %>%
  mutate(Plants = "500")

d4g10_pc_stats[[1]] <- d4g10_pc_stats[[1]] %>%
  mutate(Plants = "1000")
d4g10_bc3_stats[[1]] <- d4g10_bc3_stats[[1]] %>%
  mutate(Plants = "1000")
d4g10_gn_stats[[1]] <- d4g10_gn_stats[[1]] %>%
  mutate(Plants = "1000")
d4g10_genie_stats[[1]] <- d4g10_genie_stats[[1]] %>%
  mutate(Plants = "1000")


```

```{r}
d4g_pc_merged <- rbind(d4g0_pc_stats[[1]], d4g2_pc_stats[[1]], d4g5_pc_stats[[1]], d4g10_pc_stats[[1]])
d4g_pc_merged$Plants <- factor(d4g_pc_merged$Plants, levels=c("60", "200", "500", "1000"))

d4g_bc3_merged <- rbind(d4g0_bc3_stats[[1]], d4g2_bc3_stats[[1]], d4g5_bc3_stats[[1]], d4g10_bc3_stats[[1]])
d4g_bc3_merged$Plants <- factor(d4g_bc3_merged$Plants, levels=c("60", "200", "500", "1000"))

d4g_gn_merged <- rbind(d4g0_gn_stats[[1]], d4g2_gn_stats[[1]], d4g5_gn_stats[[1]], d4g10_gn_stats[[1]])
d4g_gn_merged$Plants <- factor(d4g_gn_merged$Plants, levels=c("60", "200", "500", "1000"))

d4g_genie_merged <- rbind(d4g0_genie_stats[[1]], d4g2_genie_stats[[1]], d4g5_genie_stats[[1]], d4g10_genie_stats[[1]])
d4g_genie_merged$Plants <- factor(d4g_genie_merged$Plants, levels=c("60", "200", "500", "1000"))


ggplot(d4g_pc_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("PC - 400 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")
ggplot(d4g_bc3_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("BC3NET - 400 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")
ggplot(d4g_gn_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("GeneNet - 400 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")
ggplot(d4g_genie_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("GENIE3 - 400 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")


```

#### 1200g

```{r}
d12g0_pc_stats[[1]] <- d12g0_pc_stats[[1]] %>%
  mutate(Plants = "60")
d12g0_bc3_stats[[1]] <- d12g0_bc3_stats[[1]] %>%
  mutate(Plants = "60")
d12g0_gn_stats[[1]] <- d12g0_gn_stats[[1]] %>%
  mutate(Plants = "60")
d12g0_genie_stats[[1]] <- d12g0_genie_stats[[1]] %>%
  mutate(Plants = "60")

d12g2_pc_stats[[1]] <- d12g2_pc_stats[[1]] %>%
  mutate(Plants = "200")
d12g2_bc3_stats[[1]] <- d12g2_bc3_stats[[1]] %>%
  mutate(Plants = "200")
d12g2_gn_stats[[1]] <- d12g2_gn_stats[[1]] %>%
  mutate(Plants = "200")
d12g2_genie_stats[[1]] <- d12g2_genie_stats[[1]] %>%
  mutate(Plants = "200")

d12g5_pc_stats[[1]] <- d12g5_pc_stats[[1]] %>%
  mutate(Plants = "500")
d12g5_bc3_stats[[1]] <- d12g5_bc3_stats[[1]] %>%
  mutate(Plants = "500")
d12g5_gn_stats[[1]] <- d12g5_gn_stats[[1]] %>%
  mutate(Plants = "500")
d12g5_genie_stats[[1]] <- d12g5_genie_stats[[1]] %>%
  mutate(Plants = "500")

#d12g10_pc_stats[[1]] <- d12g10_pc_stats[[1]] %>%
  #mutate(Plants = "1000")
d12g10_bc3_stats[[1]] <- d12g10_bc3_stats[[1]] %>%
  mutate(Plants = "1000")
d12g10_gn_stats[[1]] <- d12g10_gn_stats[[1]] %>%
  mutate(Plants = "1000")
d12g10_genie_stats[[1]] <- d12g10_genie_stats[[1]] %>%
  mutate(Plants = "1000")
```

```{r}
d12g_pc_merged <- rbind(d12g0_pc_stats[[1]], d12g2_pc_stats[[1]], d12g5_pc_stats[[1]])
d12g_pc_merged$Plants <- factor(d12g_pc_merged$Plants, levels=c("60", "200", "500", "1000"))

d12g_bc3_merged <- rbind(d12g0_bc3_stats[[1]], d12g2_bc3_stats[[1]], d12g5_bc3_stats[[1]], d12g10_bc3_stats[[1]])
d12g_bc3_merged$Plants <- factor(d12g_bc3_merged$Plants, levels=c("60", "200", "500", "1000"))

d12g_gn_merged <- rbind(d12g0_gn_stats[[1]], d12g2_gn_stats[[1]], d12g5_gn_stats[[1]], d12g10_gn_stats[[1]])
d12g_gn_merged$Plants <- factor(d12g_gn_merged$Plants, levels=c("60", "200", "500", "1000"))

d12g_genie_merged <- rbind(d12g0_genie_stats[[1]], d12g2_genie_stats[[1]], d12g5_genie_stats[[1]], d12g10_genie_stats[[1]])
d12g_genie_merged$Plants <- factor(d12g_genie_merged$Plants, levels=c("60", "200", "500", "1000"))


ggplot(d12g_pc_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("PC - 1200 Genes") +
  xlab("Observations") + ylab("Precision") +
  scale_fill_manual(values=c("#F8766D", "chartreuse3", "#619CFF")) +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
ggplot(d12g_bc3_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("BC3NET - 1200 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
ggplot(d12g_gn_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("GeneNet - 1200 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
ggplot(d12g_genie_merged, aes(x=Plants, y=prec, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("GENIE3 - 1200 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")


```
### dirty & clean
```{r}
c1g_pc_merged <- c1g_pc_merged %>%
  mutate(Noise = "clean")
d1g_pc_merged <- d1g_pc_merged %>%
  mutate(Noise = "dirty")
cd1g_pc_merged <- rbind(c1g_pc_merged, d1g_pc_merged)
cd1g_pc_merged$Plants <- factor(cd1g_pc_merged$Plants, levels=c("60", "200", "500", "1000"))

c1g_bc3_merged <- c1g_bc3_merged %>%
  mutate(Noise = "clean")
d1g_bc3_merged <- d1g_bc3_merged %>%
  mutate(Noise = "dirty")
cd1g_bc3_merged <- rbind(c1g_bc3_merged, d1g_bc3_merged)
cd1g_bc3_merged$Plants <- factor(cd1g_bc3_merged$Plants, levels=c("60", "200", "500", "1000"))

c1g_gn_merged <- c1g_gn_merged %>%
  mutate(Noise = "clean")
d1g_gn_merged <- d1g_gn_merged %>%
  mutate(Noise = "dirty")
cd1g_gn_merged <- rbind(c1g_gn_merged, d1g_gn_merged)
cd1g_gn_merged$Plants <- factor(cd1g_gn_merged$Plants, levels=c("60", "200", "500", "1000"))

c1g_genie_merged <- c1g_genie_merged %>%
  mutate(Noise = "clean")
d1g_genie_merged <- d1g_genie_merged %>%
  mutate(Noise = "dirty")
cd1g_genie_merged <- rbind(c1g_genie_merged, d1g_genie_merged)
cd1g_genie_merged$Plants <- factor(cd1g_genie_merged$Plants, levels=c("60", "200", "500", "1000"))



ggplot(cd1g_pc_merged, aes(x=Plants, y=prec, fill=Noise)) +
  geom_boxplot() + 
  ggtitle("PC - 100 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")

ggplot(cd1g_bc3_merged, aes(x=Plants, y=prec, fill=Noise)) +
  geom_boxplot() + 
  ggtitle("BC3NET - 100 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")

ggplot(cd1g_gn_merged, aes(x=Plants, y=prec, fill=Noise)) +
  geom_boxplot() + 
  ggtitle("GeneNet - 100 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")

ggplot(cd1g_genie_merged, aes(x=Plants, y=prec, fill=Noise)) +
  geom_boxplot() + 
  ggtitle("GENIE3 - 100 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
```
#### 400g
```{r}
c4g_pc_merged <- c4g_pc_merged %>%
  mutate(Noise = "clean")
d4g_pc_merged <- d4g_pc_merged %>%
  mutate(Noise = "dirty")
cd4g_pc_merged <- rbind(c4g_pc_merged, d4g_pc_merged)
cd4g_pc_merged$Plants <- factor(cd4g_pc_merged$Plants, levels=c("60", "200", "500", "1000"))

c4g_bc3_merged <- c4g_bc3_merged %>%
  mutate(Noise = "clean")
d4g_bc3_merged <- d4g_bc3_merged %>%
  mutate(Noise = "dirty")
cd4g_bc3_merged <- rbind(c4g_bc3_merged, d4g_bc3_merged)
cd4g_bc3_merged$Plants <- factor(cd4g_bc3_merged$Plants, levels=c("60", "200", "500", "1000"))

c4g_gn_merged <- c4g_gn_merged %>%
  mutate(Noise = "clean")
d4g_gn_merged <- d4g_gn_merged %>%
  mutate(Noise = "dirty")
cd4g_gn_merged <- rbind(c4g_gn_merged, d4g_gn_merged)
cd4g_gn_merged$Plants <- factor(cd4g_gn_merged$Plants, levels=c("60", "200", "500", "1000"))

c4g_genie_merged <- c4g_genie_merged %>%
  mutate(Noise = "clean")
d4g_genie_merged <- d4g_genie_merged %>%
  mutate(Noise = "dirty")
cd4g_genie_merged <- rbind(c4g_genie_merged, d4g_genie_merged)
cd4g_genie_merged$Plants <- factor(cd4g_genie_merged$Plants, levels=c("60", "200", "500", "1000"))



ggplot(cd4g_pc_merged, aes(x=Plants, y=prec, fill=Noise)) +
  geom_boxplot() + 
  ggtitle("PC - 400 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")

ggplot(cd4g_bc3_merged, aes(x=Plants, y=prec, fill=Noise)) +
  geom_boxplot() + 
  ggtitle("BC3NET - 400 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")

ggplot(cd4g_gn_merged, aes(x=Plants, y=prec, fill=Noise)) +
  geom_boxplot() + 
  ggtitle("GeneNet - 400 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")

ggplot(cd4g_genie_merged, aes(x=Plants, y=prec, fill=Noise)) +
  geom_boxplot() + 
  ggtitle("GENIE3 - 400 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")
```

#### 1200g
```{r}
c12g_pc_merged <- c12g_pc_merged %>%
  mutate(Noise = "clean")
d12g_pc_merged <- d12g_pc_merged %>%
  mutate(Noise = "dirty")
cd12g_pc_merged <- rbind(c12g_pc_merged, d12g_pc_merged)
cd12g_pc_merged$Plants <- factor(cd12g_pc_merged$Plants, levels=c("60", "200", "500", "1000"))

c12g_bc3_merged <- c12g_bc3_merged %>%
  mutate(Noise = "clean")
d12g_bc3_merged <- d12g_bc3_merged %>%
  mutate(Noise = "dirty")
cd12g_bc3_merged <- rbind(c12g_bc3_merged, d12g_bc3_merged)
cd12g_bc3_merged$Plants <- factor(cd12g_bc3_merged$Plants, levels=c("60", "200", "500", "1000"))

c12g_gn_merged <- c12g_gn_merged %>%
  mutate(Noise = "clean")
d12g_gn_merged <- d12g_gn_merged %>%
  mutate(Noise = "dirty")
cd12g_gn_merged <- rbind(c12g_gn_merged, d12g_gn_merged)
cd12g_gn_merged$Plants <- factor(cd12g_gn_merged$Plants, levels=c("60", "200", "500", "1000"))

c12g_genie_merged <- c12g_genie_merged %>%
  mutate(Noise = "clean")
d12g_genie_merged <- d12g_genie_merged %>%
  mutate(Noise = "dirty")
cd12g_genie_merged <- rbind(c12g_genie_merged, d12g_genie_merged)
cd12g_genie_merged$Plants <- factor(cd12g_genie_merged$Plants, levels=c("60", "200", "500", "1000"))



ggplot(cd12g_pc_merged, aes(x=Plants, y=prec, fill=Noise)) +
  geom_boxplot() + 
  ggtitle("PC - 1200 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")

ggplot(cd12g_bc3_merged, aes(x=Plants, y=prec, fill=Noise)) +
  geom_boxplot() + 
  ggtitle("BC3NET - 1200 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")

ggplot(cd12g_gn_merged, aes(x=Plants, y=prec, fill=Noise)) +
  geom_boxplot() + 
  ggtitle("GeneNet - 1200 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")

ggplot(cd12g_genie_merged, aes(x=Plants, y=prec, fill=Noise)) +
  geom_boxplot() + 
  ggtitle("GENIE3 - 1200 Genes") +
  xlab("Observations") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
```



## Number of proposed associations ~ observations

```{r}
ggplot(d1g_pc_merged, aes(x=Plants, y=PP, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("PC - 100 Genes") +
  xlab("Observations") + ylab("Proposed associations") 
  #coord_cartesian(ylim=c(0, 0.15)) +
  #geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
ggplot(d1g_bc3_merged, aes(x=Plants, y=PP, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("BC3NET - 100 Genes") +
  xlab("Observations") + ylab("Proposed associations") 
ggplot(d1g_gn_merged, aes(x=Plants, y=PP, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("GeneNet - 100 Genes") +
  xlab("Observations") + ylab("Proposed associations") 
ggplot(d1g_genie_merged, aes(x=Plants, y=PP, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("GENIE3 - 100 Genes") +
  xlab("Observations") + ylab("Proposed associations") 

ggplot(d4g_pc_merged, aes(x=Plants, y=PP, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("PC - 400 Genes") +
  xlab("Observations") + ylab("Proposed associations") 
  #coord_cartesian(ylim=c(0, 0.15)) +
  #geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
ggplot(d4g_bc3_merged, aes(x=Plants, y=PP, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("BC3NET - 400 Genes") +
  xlab("Observations") + ylab("Proposed associations") 
ggplot(d4g_gn_merged, aes(x=Plants, y=PP, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("GeneNet - 400 Genes") +
  xlab("Observations") + ylab("Proposed associations") 
ggplot(d4g_genie_merged, aes(x=Plants, y=PP, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("GENIE3 - 400 Genes") +
  xlab("Observations") + ylab("Proposed associations")


ggplot(d12g_pc_merged, aes(x=Plants, y=PP, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("PC - 1200 Genes") +
  xlab("Observations") + ylab("Proposed associations") 
ggplot(d12g_bc3_merged, aes(x=Plants, y=PP, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("BC3NET - 1200 Genes") +
  xlab("Observations") + ylab("Proposed associations") 
ggplot(d12g_gn_merged, aes(x=Plants, y=PP, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("GeneNet - 1200 Genes") +
  xlab("Observations") + ylab("Proposed associations") 
ggplot(d12g_genie_merged, aes(x=Plants, y=PP, fill=Plants)) +
  geom_boxplot() + 
  ggtitle("GENIE3 - 1200 Genes") +
  xlab("Observations") + ylab("Proposed associations")
```

## Precision in function of inference methods

### 100g
```{r}
d1g0_merged <- rbind(d1g0_pc_stats[[1]], d1g0_bc3_stats[[1]], d1g0_genie_stats[[1]])
d1g2_merged <- rbind(d1g2_pc_stats[[1]], d1g2_bc3_stats[[1]], d1g2_genie_stats[[1]])
d1g5_merged <- rbind(d1g5_pc_stats[[1]], d1g5_bc3_stats[[1]], d1g5_genie_stats[[1]])
d1g10_merged <- rbind(d1g10_pc_stats[[1]], d1g10_bc3_stats[[1]], d1g10_genie_stats[[1]])

plot1 <- ggplot(d1g0_merged, aes(x=method, y=prec, fill=method)) +
  geom_boxplot() + 
  ggtitle("100 Genes - 60 Cells") +
  xlab("Methods") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
plot2 <- ggplot(d1g2_merged, aes(x=method, y=prec, fill=method)) +
  geom_boxplot() + 
  ggtitle("100 Genes - 200 Cells") +
  xlab("Methods") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
plot3 <- ggplot(d1g5_merged, aes(x=method, y=prec, fill=method)) +
  geom_boxplot() + 
  ggtitle("100 Genes - 500 Cells") +
  xlab("Methods") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
plot4 <- ggplot(d1g10_merged, aes(x=method, y=prec, fill=method)) +
  geom_boxplot() + 
  ggtitle("100 Genes - 1000 Cells") +
  xlab("Methods") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")

grid.arrange(plot1, plot2, ncol=2)
grid.arrange(plot3, plot4, ncol=2)
```
### 400g
```{r}
d4g0_merged <- rbind(d4g0_pc_stats[[1]], d4g0_bc3_stats[[1]], d4g0_genie_stats[[1]])
d4g2_merged <- rbind(d4g2_pc_stats[[1]], d4g2_bc3_stats[[1]], d4g2_genie_stats[[1]])
d4g5_merged <- rbind(d4g5_pc_stats[[1]], d4g5_bc3_stats[[1]], d4g5_genie_stats[[1]])
d4g10_merged <- rbind(d4g10_pc_stats[[1]], d4g10_bc3_stats[[1]], d4g10_genie_stats[[1]])

plot1 <- ggplot(d4g0_merged, aes(x=method, y=prec, fill=method)) +
  geom_boxplot() + 
  ggtitle("400 Genes - 60 Cells") +
  xlab("Methods") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")
plot2 <- ggplot(d4g2_merged, aes(x=method, y=prec, fill=method)) +
  geom_boxplot() + 
  ggtitle("400 Genes - 200 Cells") +
  xlab("Methods") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")
plot3 <- ggplot(d4g5_merged, aes(x=method, y=prec, fill=method)) +
  geom_boxplot() + 
  ggtitle("400 Genes - 500 Cells") +
  xlab("Methods") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")
plot4 <- ggplot(d4g10_merged, aes(x=method, y=prec, fill=method)) +
  geom_boxplot() + 
  ggtitle("400 Genes - 1000 Cells") +
  xlab("Methods") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")

grid.arrange(plot1, plot2, ncol=2)
grid.arrange(plot3, plot4, ncol=2)
```
### 1200g
```{r}
d12g0_merged <- rbind(d12g0_pc_stats[[1]], d12g0_bc3_stats[[1]], d12g0_genie_stats[[1]])
d12g2_merged <- rbind(d12g2_pc_stats[[1]], d12g2_bc3_stats[[1]], d12g2_genie_stats[[1]])
d12g5_merged <- rbind(d12g5_pc_stats[[1]], d12g5_bc3_stats[[1]], d12g5_genie_stats[[1]])
d12g10_merged <- rbind(d12g10_bc3_stats[[1]], d12g10_genie_stats[[1]])

plot1 <- ggplot(d12g0_merged, aes(x=method, y=prec, fill=method)) +
  geom_boxplot() + 
  ggtitle("1200 Genes - 60 Cells") +
  xlab("Methods") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
plot2 <- ggplot(d12g2_merged, aes(x=method, y=prec, fill=method)) +
  geom_boxplot() + 
  ggtitle("1200 Genes - 200 Cells") +
  xlab("Methods") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
plot3 <- ggplot(d12g5_merged, aes(x=method, y=prec, fill=method)) +
  geom_boxplot() + 
  ggtitle("1200 Genes - 500 Cells") +
  xlab("Methods") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
plot4 <- ggplot(d12g10_merged, aes(x=method, y=prec, fill=method)) +
  geom_boxplot() + 
  ggtitle("1200 Genes - 1000 Cells") +
  xlab("Methods") + ylab("Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red") +
  scale_fill_manual(values=c("coral1", "limegreen"))

grid.arrange(plot1, plot2, ncol=2)
grid.arrange(plot3, plot4, ncol=2)
```



## Ranked Precision

```{r}
pc_rank <- d1g5_pc_stats[[2]][[2]] %>%
  filter(count >= 50)
bc3_rank <- d1g5_bc3_stats[[2]][[2]] %>%
  filter(count >= 50)
gn_rank <- d1g5_gn_stats[[2]][[2]] %>%
  filter(count >= 50)
genie_rank <- d1g5_genie_stats[[2]][[2]] %>%
  filter(count >= 50)
```

```{r}
plot_pc_1 <- ggplot(pc_rank, aes(x=rank, y=rank_precision_adj)) +
  geom_smooth() +
  ggtitle("PC") +
  xlab("Rank") + ylab("Ranked Precision (adjusted, 50+ edges)") +
  coord_cartesian(ylim=c(0, 0.3)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
plot_pc_2 <- ggplot(d1g5_pc_stats[[2]][[2]], aes(x=rank, y=rank_precision_adj)) +
  geom_smooth() +
  ggtitle("PC") +
  xlab("Rank") + ylab("Ranked Precision (adjusted)") +
  coord_cartesian(ylim=c(0, 0.3)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
plot_pc_3 <- ggplot(d1g5_pc_stats[[2]][[2]], aes(x=rank, y=rank_precision)) +
  geom_smooth() +
  ggtitle("PC") +
  xlab("Rank") + ylab("Ranked Precision") +
  coord_cartesian(ylim=c(0, 0.3)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")

plot_bc3_1 <- ggplot(bc3_rank, aes(x=rank, y=rank_precision_adj)) +
  geom_smooth() +
  ggtitle("BC3NET") +
  xlab("Rank") + ylab("Ranked Precision (adjusted, 50+ edges)") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
plot_bc3_2 <- ggplot(d1g5_bc3_stats[[2]][[2]], aes(x=rank, y=rank_precision_adj)) +
  geom_smooth() +
  ggtitle("BC3NET") +
  xlab("Rank") + ylab("Ranked Precision (adjusted)") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
plot_bc3_3 <- ggplot(d1g5_bc3_stats[[2]][[2]], aes(x=rank, y=rank_precision)) +
  geom_smooth() +
  ggtitle("BC3NET") +
  xlab("Rank") + ylab("Ranked Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")

plot_genie_1 <- ggplot(genie_rank, aes(x=rank, y=rank_precision_adj)) +
  geom_smooth() +
  ggtitle("GENIE3") +
  xlab("Rank") + ylab("Ranked Precision (adjusted, 50+ edges)") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
plot_genie_2 <- ggplot(d1g5_genie_stats[[2]][[2]], aes(x=rank, y=rank_precision_adj)) +
  geom_smooth() +
  ggtitle("GENIE3") +
  xlab("Rank") + ylab("Ranked Precision (adjusted)") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
plot_genie_3 <- ggplot(d1g5_genie_stats[[2]][[2]], aes(x=rank, y=rank_precision)) +
  geom_smooth() +
  ggtitle("GENIE3") +
  xlab("Rank") + ylab("Ranked Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")

grid.arrange(plot_pc_1, plot_bc3_1, plot_genie_1, ncol=3)
```

```{r}
d1g0_pc_stats[[2]][[2]] <- d1g0_pc_stats[[2]][[2]] %>%
  mutate(method="pc")
d1g2_pc_stats[[2]][[2]] <- d1g2_pc_stats[[2]][[2]] %>%
  mutate(method="pc")
d1g5_pc_stats[[2]][[2]] <- d1g5_pc_stats[[2]][[2]] %>%
  mutate(method="pc")
d1g10_pc_stats[[2]][[2]] <- d1g10_pc_stats[[2]][[2]] %>%
  mutate(method="pc")

d1g0_bc3_stats[[2]][[2]] <- d1g0_bc3_stats[[2]][[2]] %>%
  mutate(method="bc3")
d1g2_bc3_stats[[2]][[2]] <- d1g2_bc3_stats[[2]][[2]] %>%
  mutate(method="bc3")
d1g5_bc3_stats[[2]][[2]] <- d1g5_bc3_stats[[2]][[2]] %>%
  mutate(method="bc3")
d1g10_bc3_stats[[2]][[2]] <- d1g10_bc3_stats[[2]][[2]] %>%
  mutate(method="bc3")

d1g0_genie_stats[[2]][[2]] <- d1g0_genie_stats[[2]][[2]] %>%
  mutate(method="genie")
d1g2_genie_stats[[2]][[2]] <- d1g2_genie_stats[[2]][[2]] %>%
  mutate(method="genie")
d1g5_genie_stats[[2]][[2]] <- d1g5_genie_stats[[2]][[2]] %>%
  mutate(method="genie")
d1g10_genie_stats[[2]][[2]] <- d1g10_genie_stats[[2]][[2]] %>%
  mutate(method="genie")


d1g0_merged <- rbind(d1g0_pc_stats[[2]][[2]], d1g0_bc3_stats[[2]][[2]], d1g0_genie_stats[[2]][[2]]) %>%
  filter(count >= 50)
d1g2_merged <- rbind(d1g2_pc_stats[[2]][[2]], d1g2_bc3_stats[[2]][[2]], d1g2_genie_stats[[2]][[2]]) %>%
  filter(count >= 50)
d1g5_merged <- rbind(d1g5_pc_stats[[2]][[2]], d1g5_bc3_stats[[2]][[2]], d1g5_genie_stats[[2]][[2]]) %>%
  filter(count >= 50)
d1g10_merged <- rbind(d1g10_pc_stats[[2]][[2]], d1g10_bc3_stats[[2]][[2]], d1g10_genie_stats[[2]][[2]]) %>%
  filter(count >= 50)

ggplot(d1g0_merged, aes(x=rank, y=rank_precision_adj, color=method)) +
  geom_smooth() +
  ggtitle("100 Genes - 60 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  coord_cartesian(ylim=c(0, 0.3)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
ggplot(d1g2_merged, aes(x=rank, y=rank_precision_adj, color=method)) +
  geom_smooth() +
  ggtitle("200 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  coord_cartesian(ylim=c(0, 0.3)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
ggplot(d1g5_merged, aes(x=rank, y=rank_precision_adj, color=method)) +
  geom_smooth() +
  ggtitle("500 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  coord_cartesian(ylim=c(0, 0.3)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
ggplot(d1g10_merged, aes(x=rank, y=rank_precision_adj, color=method)) +
  geom_smooth() +
  ggtitle("1000 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  coord_cartesian(ylim=c(0, 0.3)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
```

```{r}
d4g0_pc_stats[[2]][[2]] <- d4g0_pc_stats[[2]][[2]] %>%
  mutate(method="pc")
d4g2_pc_stats[[2]][[2]] <- d4g2_pc_stats[[2]][[2]] %>%
  mutate(method="pc")
d4g5_pc_stats[[2]][[2]] <- d4g5_pc_stats[[2]][[2]] %>%
  mutate(method="pc")
d4g10_pc_stats[[2]][[2]] <- d4g10_pc_stats[[2]][[2]] %>%
  mutate(method="pc")

d4g0_bc3_stats[[2]][[2]] <- d4g0_bc3_stats[[2]][[2]] %>%
  mutate(method="bc3")
d4g2_bc3_stats[[2]][[2]] <- d4g2_bc3_stats[[2]][[2]] %>%
  mutate(method="bc3")
d4g5_bc3_stats[[2]][[2]] <- d4g5_bc3_stats[[2]][[2]] %>%
  mutate(method="bc3")
d4g10_bc3_stats[[2]][[2]] <- d4g10_bc3_stats[[2]][[2]] %>%
  mutate(method="bc3")

d4g0_genie_stats[[2]][[2]] <- d4g0_genie_stats[[2]][[2]] %>%
  mutate(method="genie")
d4g2_genie_stats[[2]][[2]] <- d4g2_genie_stats[[2]][[2]] %>%
  mutate(method="genie")
d4g5_genie_stats[[2]][[2]] <- d4g5_genie_stats[[2]][[2]] %>%
  mutate(method="genie")
d4g10_genie_stats[[2]][[2]] <- d4g10_genie_stats[[2]][[2]] %>%
  mutate(method="genie")


d4g0_merged <- rbind(d4g0_pc_stats[[2]][[2]], d4g0_bc3_stats[[2]][[2]], d4g0_genie_stats[[2]][[2]]) %>%
  filter(count >= 50)
d4g2_merged <- rbind(d4g2_pc_stats[[2]][[2]], d4g2_bc3_stats[[2]][[2]], d4g2_genie_stats[[2]][[2]]) %>%
  filter(count >= 50)
d4g5_merged <- rbind(d4g5_pc_stats[[2]][[2]], d4g5_bc3_stats[[2]][[2]], d4g5_genie_stats[[2]][[2]]) %>%
  filter(count >= 50)
d4g10_merged <- rbind(d4g10_pc_stats[[2]][[2]], d4g10_bc3_stats[[2]][[2]], d4g10_genie_stats[[2]][[2]]) %>%
  filter(count >= 50)

ggplot(d4g0_merged, aes(x=rank, y=rank_precision_adj, color=method)) +
  geom_smooth() +
  ggtitle("400 Genes - 60 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  coord_cartesian(ylim=c(0, 0.05)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")
ggplot(d4g2_merged, aes(x=rank, y=rank_precision_adj, color=method)) +
  geom_smooth() +
  ggtitle("200 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  coord_cartesian(ylim=c(0, 0.1)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")
ggplot(d4g5_merged, aes(x=rank, y=rank_precision_adj, color=method)) +
  geom_smooth() +
  ggtitle("500 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")
ggplot(d4g10_merged, aes(x=rank, y=rank_precision_adj, color=method)) +
  geom_smooth() +
  geom_point() +
  ggtitle("1000 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  #coord_cartesian(ylim=c(0, 0.25)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")
```


```{r}
d12g0_pc_stats[[2]][[2]] <- d12g0_pc_stats[[2]][[2]] %>%
  mutate(method="pc")
d12g2_pc_stats[[2]][[2]] <- d12g2_pc_stats[[2]][[2]] %>%
  mutate(method="pc")
d12g5_pc_stats[[2]][[2]] <- d12g5_pc_stats[[2]][[2]] %>%
  mutate(method="pc")

d12g0_bc3_stats[[2]][[2]] <- d12g0_bc3_stats[[2]][[2]] %>%
  mutate(method="bc3")
d12g2_bc3_stats[[2]][[2]] <- d12g2_bc3_stats[[2]][[2]] %>%
  mutate(method="bc3")
d12g5_bc3_stats[[2]][[2]] <- d12g5_bc3_stats[[2]][[2]] %>%
  mutate(method="bc3")
d12g10_bc3_stats[[2]][[2]] <- d12g10_bc3_stats[[2]][[2]] %>%
  mutate(method="bc3")

d12g0_genie_stats[[2]][[2]] <- d12g0_genie_stats[[2]][[2]] %>%
  mutate(method="genie")
d12g2_genie_stats[[2]][[2]] <- d12g2_genie_stats[[2]][[2]] %>%
  mutate(method="genie")
d12g5_genie_stats[[2]][[2]] <- d12g5_genie_stats[[2]][[2]] %>%
  mutate(method="genie")
d12g10_genie_stats[[2]][[2]] <- d12g10_genie_stats[[2]][[2]] %>%
  mutate(method="genie")


d12g0_merged <- rbind(d12g0_pc_stats[[2]][[2]], d12g0_bc3_stats[[2]][[2]], d12g0_genie_stats[[2]][[2]]) %>%
  filter(count >= 50)
d12g2_merged <- rbind(d12g2_pc_stats[[2]][[2]], d12g2_bc3_stats[[2]][[2]], d12g2_genie_stats[[2]][[2]]) %>%
  filter(count >= 50)
d12g5_merged <- rbind(d12g5_pc_stats[[2]][[2]], d12g5_bc3_stats[[2]][[2]], d12g5_genie_stats[[2]][[2]]) %>%
  filter(count >= 50)
d12g10_merged <- rbind(d12g10_bc3_stats[[2]][[2]], d12g10_genie_stats[[2]][[2]]) %>%
  filter(count >= 50)

d12g10_merged$method <- factor(d12g10_merged$method, levels=c("bc3", "genie"))

ggplot(d12g0_merged, aes(x=rank, y=rank_precision_adj, color=method)) +
  geom_smooth() +
  ggtitle("1200 Genes - 60 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  coord_cartesian(ylim=c(0, 0.15), xlim=c(0, 100)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
ggplot(d12g2_merged, aes(x=rank, y=rank_precision_adj, color=method)) +
  geom_smooth() +
  ggtitle("200 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
ggplot(d12g5_merged, aes(x=rank, y=rank_precision_adj, color=method)) +
  geom_smooth() +
  ggtitle("500 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  coord_cartesian(ylim=c(0, 0.15)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
ggplot(d12g10_merged, aes(x=rank, y=rank_precision_adj, color=method)) +
  geom_smooth() +
  scale_color_manual(values=c("#F8766D", "chartreuse3")) +
  ggtitle("1000 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  #coord_cartesian(ylim=c(0, 0.4)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
```


### Ranked precision top ranks
```{r}
d4g10_merged <- rbind(d4g10_bc3_stats[[2]][[2]], d4g10_genie_stats[[2]][[2]]) %>%
  filter(count >= 50) %>%
  filter(rank <= 250)
d1g10_merged <- rbind(d1g10_bc3_stats[[2]][[2]], d1g10_genie_stats[[2]][[2]]) %>%
  filter(count >= 50) %>%
  filter(rank <= 250)

d1g5_pc_rankprec <- d1g5_pc_stats[[2]][[2]] %>%
  filter(count >= 50) 
d4g5_pc_rankprec <- d4g5_pc_stats[[2]][[2]] %>%
  filter(count >= 50) %>%
  filter(rank <= 250)
d12g5_pc_rankprec <- d12g5_pc_stats[[2]][[2]] %>%
  filter(count >= 50)

d4g10_pc_rankprec <- d4g10_pc_stats[[2]][[2]] %>%
  filter(count >= 50) %>%
  filter(rank <= 250)
d1g10_pc_rankprec <- d1g10_pc_stats[[2]][[2]] %>%
  filter(count >= 50) %>%
  filter(rank <= 250)


ggplot(d12g10_merged, aes(x=rank, y=rank_precision_adj, color=method)) +
  geom_smooth() +
  geom_point() +
  ggtitle("1200 Genes - 1000 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  #coord_cartesian(ylim=c(0, 0.4)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
ggplot(d4g10_merged, aes(x=rank, y=rank_precision_adj, color=method)) +
  geom_smooth() +
  geom_point() +
  ggtitle("400 Genes - 1000 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  #coord_cartesian(ylim=c(0, 0.25)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")
ggplot(d1g10_merged, aes(x=rank, y=rank_precision_adj, color=method)) +
  geom_smooth() +
  geom_point() +
  ggtitle("100 Genes - 1000 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  #coord_cartesian(ylim=c(0, 0.25)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")

ggplot(d12g5_pc_rankprec, aes(x=rank, y=rank_precision_adj)) +
  geom_smooth() +
  geom_point() +
  ggtitle("PC: 1200 genes - 500 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  #coord_cartesian(ylim=c(0, 0.05)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
ggplot(d4g5_pc_rankprec, aes(x=rank, y=rank_precision_adj)) +
  geom_smooth() +
  geom_point() +
  ggtitle("PC: 400 genes - 500 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  #coord_cartesian(ylim=c(0, 0.05)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")
ggplot(d1g5_pc_rankprec, aes(x=rank, y=rank_precision_adj)) +
  geom_smooth() +
  geom_point() +
  ggtitle("PC: 100 genes - 500 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  #coord_cartesian(ylim=c(0, 0.05)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")

c1g5_pc_rankprec <- c1g5_pc_stats[[2]][[2]] %>%
  filter(count >= 50) %>%
  filter(rank <= 250)
c4g5_pc_rankprec <- c4g5_pc_stats[[2]][[2]] %>%
  filter(count >= 50) %>%
  filter(rank <= 250)
c12g5_pc_rankprec <- c12g5_pc_stats[[2]][[2]] %>%
  filter(count >= 50) %>%
  filter(rank <= 250)

ggplot(c12g5_pc_rankprec, aes(x=rank, y=rank_precision_adj)) +
  geom_smooth() +
  geom_point() +
  ggtitle("PC: 1200 genes - 500 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  #coord_cartesian(ylim=c(0, 0.05)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
ggplot(c4g5_pc_rankprec, aes(x=rank, y=rank_precision_adj)) +
  geom_smooth() +
  geom_point() +
  ggtitle("PC: 400 genes - 500 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  #coord_cartesian(ylim=c(0, 0.05)) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red")
ggplot(c1g5_pc_rankprec, aes(x=rank, y=rank_precision_adj)) +
  geom_smooth() +
  geom_point() +
  ggtitle("PC: 100 genes - 500 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  #coord_cartesian(ylim=c(0, 0.05)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")

ggplot(d1g10_pc_rankprec, aes(x=rank, y=rank_precision_adj)) +
  geom_smooth() +
  geom_point() +
  ggtitle("PC: 100 genes - 1000 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  #coord_cartesian(ylim=c(0, 0.05)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")
ggplot(d1g5_pc_rankprec, aes(x=rank, y=rank_precision_adj)) +
  geom_smooth() +
  geom_point() +
  ggtitle("PC: 100 genes - 500 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  #coord_cartesian(ylim=c(0, 0.05)) +
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red")


```

```{r}
lol <- c12g10_genie_stats[[2]][[2]] %>%
  mutate(method="genie") %>%
  filter(count >= 50, rank <= 250)


ggplot(lol, aes(x=rank, y=rank_precision_adj, color=method)) +
  geom_smooth() +
  geom_point() +
  ggtitle("1200 Genes - 1000 Plants") +
  xlab("Rank") + ylab("Ranked Precision") +
  #coord_cartesian(ylim=c(0, 0.4)) +
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
```




## Recall vs observations
### dirty & clean
#### 400g
```{r}
c4g_pc_merged <- c4g_pc_merged %>%
  mutate(Noise = "clean")
d4g_pc_merged <- d4g_pc_merged %>%
  mutate(Noise = "dirty")
cd4g_pc_merged <- rbind(c4g_pc_merged, d4g_pc_merged)
cd4g_pc_merged$Plants <- factor(cd4g_pc_merged$Plants, levels=c("60", "200", "500", "1000"))

c4g_bc3_merged <- c4g_bc3_merged %>%
  mutate(Noise = "clean")
d4g_bc3_merged <- d4g_bc3_merged %>%
  mutate(Noise = "dirty")
cd4g_bc3_merged <- rbind(c4g_bc3_merged, d4g_bc3_merged)
cd4g_bc3_merged$Plants <- factor(cd4g_bc3_merged$Plants, levels=c("60", "200", "500", "1000"))

c4g_gn_merged <- c4g_gn_merged %>%
  mutate(Noise = "clean")
d4g_gn_merged <- d4g_gn_merged %>%
  mutate(Noise = "dirty")
cd4g_gn_merged <- rbind(c4g_gn_merged, d4g_gn_merged)
cd4g_gn_merged$Plants <- factor(cd4g_gn_merged$Plants, levels=c("60", "200", "500", "1000"))

c4g_genie_merged <- c4g_genie_merged %>%
  mutate(Noise = "clean")
d4g_genie_merged <- d4g_genie_merged %>%
  mutate(Noise = "dirty")
cd4g_genie_merged <- rbind(c4g_genie_merged, d4g_genie_merged)
cd4g_genie_merged$Plants <- factor(cd4g_genie_merged$Plants, levels=c("60", "200", "500", "1000"))



ggplot(cd4g_pc_merged, aes(x=Plants, y=rec, fill=Noise)) +
  geom_boxplot() + 
  ggtitle("PC - 400 Genes") +
  xlab("Observations") + ylab("Recall") +
  coord_cartesian(ylim=c(0, 0.15))

ggplot(cd4g_bc3_merged, aes(x=Plants, y=rec, fill=Noise)) +
  geom_boxplot() + 
  ggtitle("BC3NET - 400 Genes") +
  xlab("Observations") + ylab("Recall") +
  coord_cartesian(ylim=c(0, 0.15))

ggplot(cd4g_gn_merged, aes(x=Plants, y=rec, fill=Noise)) +
  geom_boxplot() + 
  ggtitle("GeneNet - 400 Genes") +
  xlab("Observations") + ylab("Recall") +
  coord_cartesian(ylim=c(0, 0.15)) 

ggplot(cd4g_genie_merged, aes(x=Plants, y=rec, fill=Noise)) +
  geom_boxplot() + 
  ggtitle("GENIE3 - 400 Genes") +
  xlab("Observations") + ylab("Recall") +
  coord_cartesian(ylim=c(0, 0.15)) 
```










## PRC
### 100g
#### 1000c
```{r}
end_rank_genie <- nrow(filter(d1g10_genie_stats[[2]][[2]], count >= 50))
end_rank_bc3 <- nrow(filter(d1g10_bc3_stats[[2]][[2]], count >= 50))
end_rank_pc <- nrow(filter(d1g10_pc_stats[[2]][[2]], count >= 50))

genie_prc <- filter(d1g10_genie_stats[[2]][[1]], rank <= end_rank_genie) %>%
  group_by(rank) %>%
  summarise(TP = sum(TP), count = sum(rank) / mean(rank)) %>%
  mutate(cumTP = cumsum(TP), rec = (TP / count) / nrow(true_grn1)) %>%
  mutate(cumcount = cumsum(count), cumrec = cumsum(rec)) %>%
  mutate(cumprec = cumTP / cumcount) %>%
  mutate(F1 = (2*cumrec*cumprec)/(cumrec+cumprec)) %>%
  mutate(method = 'genie')
bc3_prc <- filter(d1g10_bc3_stats[[2]][[1]], rank <= end_rank_bc3) %>%
  group_by(rank) %>%
  summarise(TP = sum(TP), count = sum(rank) / mean(rank)) %>%
  mutate(cumTP = cumsum(TP), rec = (TP / count) / nrow(true_grn1)) %>%
  mutate(cumcount = cumsum(count), cumrec = cumsum(rec)) %>%
  mutate(cumprec = cumTP / cumcount) %>%
  mutate(F1 = (2*cumrec*cumprec)/(cumrec+cumprec)) %>%
  mutate(method = 'bc3net')
pc_prc <- filter(d1g10_pc_stats[[2]][[1]], rank <= end_rank_pc) %>%
  group_by(rank) %>%
  summarise(TP = sum(TP), count = sum(rank) / mean(rank)) %>%
  mutate(cumTP = cumsum(TP), rec = (TP / count) / nrow(true_grn1)) %>%
  mutate(cumcount = cumsum(count), cumrec = cumsum(rec)) %>%
  mutate(cumprec = cumTP / cumcount) %>%
  mutate(F1 = (2*cumrec*cumprec)/(cumrec+cumprec)) %>%
  mutate(method = 'pc')

minrec <- min(c(max(genie_prc$cumrec), max(bc3_prc$cumrec), max(pc_prc$cumrec)))
genie_auc_rank <- filter(genie_prc, cumrec <= minrec)
bc3_auc_rank <- filter(bc3_prc, cumrec <= minrec)
pc_auc_rank <- filter(pc_prc, cumrec <= minrec)

auc_1g <- c(calc_auc(genie_auc_rank), calc_auc(bc3_auc_rank), calc_auc(pc_auc_rank))
F1_1g <- rbind(arrange(genie_prc, desc(F1))[1,], arrange(bc3_prc, desc(F1))[1,], arrange(pc_prc, desc(F1))[1,])

merged <- rbind(genie_prc, bc3_prc, pc_prc) 
merged$method <- factor(merged$method, levels=c("bc3net", "pc", "genie"))

ggplot(merged, aes(x=cumrec, y=cumprec, color=method)) +
  geom_line() +
  ggtitle("PRC: 100 Genes - 1000 Plants") +
  xlab("Recall") + ylab("Precision") + 
  geom_hline(yintercept=exp_precision1, linetype="dashed", color="red") +
  coord_cartesian(ylim=c(0, NA)) 
```

### 400g
#### 1000c
```{r}
end_rank_genie <- nrow(filter(d4g10_genie_stats[[2]][[2]], count >= 50))
end_rank_bc3 <- nrow(filter(d4g10_bc3_stats[[2]][[2]], count >= 50))
end_rank_pc <- nrow(filter(d4g10_pc_stats[[2]][[2]], count >= 50))

genie_prc <- filter(d4g10_genie_stats[[2]][[1]], rank <= end_rank_genie) %>%
  group_by(rank) %>%
  summarise(TP = sum(TP), count = sum(rank) / mean(rank)) %>%
  mutate(cumTP = cumsum(TP), rec = (TP / count) / nrow(true_grn4)) %>%
  mutate(cumcount = cumsum(count), cumrec = cumsum(rec)) %>%
  mutate(cumprec = cumTP / cumcount) %>%
  mutate(F1 = (2*cumrec*cumprec)/(cumrec+cumprec)) %>%
  mutate(method = 'genie')
bc3_prc <- filter(d4g10_bc3_stats[[2]][[1]], rank <= end_rank_bc3) %>%
  group_by(rank) %>%
  summarise(TP = sum(TP), count = sum(rank) / mean(rank)) %>%
  mutate(cumTP = cumsum(TP), rec = (TP / count) / nrow(true_grn4)) %>%
  mutate(cumcount = cumsum(count), cumrec = cumsum(rec)) %>%
  mutate(cumprec = cumTP / cumcount) %>%
  mutate(F1 = (2*cumrec*cumprec)/(cumrec+cumprec)) %>%
  mutate(method = 'bc3net')
pc_prc <- filter(d4g10_pc_stats[[2]][[1]], rank <= end_rank_pc) %>%
  group_by(rank) %>%
  summarise(TP = sum(TP), count = sum(rank) / mean(rank)) %>%
  mutate(cumTP = cumsum(TP), rec = (TP / count) / nrow(true_grn4)) %>%
  mutate(cumcount = cumsum(count), cumrec = cumsum(rec)) %>%
  mutate(cumprec = cumTP / cumcount) %>%
  mutate(F1 = (2*cumrec*cumprec)/(cumrec+cumprec)) %>%
  mutate(method = 'pc')

minrec <- min(c(max(genie_prc$cumrec), max(bc3_prc$cumrec), max(pc_prc$cumrec)))
genie_auc_rank <- filter(genie_prc, cumrec <= minrec)
bc3_auc_rank <- filter(bc3_prc, cumrec <= minrec)
pc_auc_rank <- filter(pc_prc, cumrec <= minrec)

auc_4g <- c(calc_auc(genie_auc_rank), calc_auc(bc3_auc_rank), calc_auc(pc_auc_rank))
F1_4g <- rbind(arrange(genie_prc, desc(F1))[1,], arrange(bc3_prc, desc(F1))[1,], arrange(pc_prc, desc(F1))[1,])

merged <- rbind(genie_prc,  pc_prc) 
merged$method <- factor(merged$method, levels=c("bc3net", "pc", "genie"))

ggplot(merged, aes(x=cumrec, y=cumprec, color=method)) +
  geom_line() +
  ggtitle("400 Genes - 1000 Plants | Undirected precision") +
  xlab("Recall") + ylab("Precision") + 
  scale_color_manual(values=c("#00BA38", "#619CFF")) +
  geom_hline(yintercept=exp_precision4, linetype="dashed", color="red") +
  coord_cartesian(ylim=c(0, 0.5), xlim=c(0, 0.1)) 
```

### 1200g
#### 1000c
```{r}
end_rank_genie <- nrow(filter(d12g10_genie_stats[[2]][[2]], count >= 50))
genie_prc <- filter(d12g10_genie_stats[[2]][[1]], rank <= end_rank_genie) %>%
 group_by(rank) %>%
  summarise(TP = sum(TP), count = sum(rank) / mean(rank)) %>%
  mutate(cumTP = cumsum(TP), rec = (TP / count) / nrow(true_grn12)) %>%
  mutate(cumcount = cumsum(count), cumrec = cumsum(rec)) %>%
  mutate(cumprec = cumTP / cumcount) %>%
  mutate(F1 = (2*cumrec*cumprec)/(cumrec+cumprec)) %>%
  mutate(method = 'genie')

end_rank_bc3 <- nrow(filter(d12g10_bc3_stats[[2]][[2]], count >= 50))
bc3_prc <- filter(d12g10_bc3_stats[[2]][[1]], rank <= end_rank_bc3) %>%
  group_by(rank) %>%
  summarise(TP = sum(TP), count = sum(rank) / mean(rank)) %>%
  mutate(cumTP = cumsum(TP), rec = (TP / count) / nrow(true_grn12)) %>%
  mutate(cumcount = cumsum(count), cumrec = cumsum(rec)) %>%
  mutate(cumprec = cumTP / cumcount) %>%
  mutate(F1 = (2*cumrec*cumprec)/(cumrec+cumprec)) %>%
  mutate(method = 'bc3net')

minrec <- min(c(max(genie_prc$cumrec), max(bc3_prc$cumrec), max(pc_prc$cumrec)))
genie_auc_rank <- filter(genie_prc, cumrec <= minrec)
bc3_auc_rank <- filter(bc3_prc, cumrec <= minrec)

auc_12g <- c(calc_auc(genie_auc_rank), calc_auc(bc3_auc_rank), calc_auc(pc_auc_rank))
F1_12g <- rbind(arrange(genie_prc, desc(F1))[1,], arrange(bc3_prc, desc(F1))[1,])

merged <- rbind(genie_prc, bc3_prc)     

ggplot(genie_prc, aes(x=cumrec, y=cumprec)) +
  geom_line() +
  ggtitle("GENIE3: 1200 Genes - 1000 Plants") +
  xlab("Recall") + ylab("Precision") + 
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
ggplot(bc3_prc, aes(x=cumrec, y=cumprec)) +
  geom_line() +
  ggtitle("GENIE3: 1200 Genes - 1000 Plants") +
  xlab("Recall") + ylab("Precision") + 
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
ggplot(merged, aes(x=cumrec, y=cumprec, color=method)) +
  geom_line() +
  ggtitle("PRC: 1200 Genes - 1000 Plants") +
  xlab("Recall") + ylab("Precision") + 
  geom_hline(yintercept=exp_precision12, linetype="dashed", color="red")
```

## SIGN ACCURACY

### ACCURACY
```{r}
d1_pc_sign <- c(calc_sign(d1g0_pc_stats, true_grn1, pc = TRUE, val = "score"),
                calc_sign(d1g2_pc_stats, true_grn1, pc = TRUE, val = "score"),
                calc_sign(d1g5_pc_stats, true_grn1, pc = TRUE, val = "score"),
                calc_sign(d1g10_pc_stats, true_grn1, pc = TRUE, val = "score"))
d4_pc_sign <- c(calc_sign(d4g0_pc_stats, true_grn4, pc = TRUE, val = "score"),
                calc_sign(d4g2_pc_stats, true_grn4, pc = TRUE, val = "score"),
                calc_sign(d4g5_pc_stats, true_grn4, pc = TRUE, val = "score"),
                calc_sign(d4g10_pc_stats, true_grn4, pc = TRUE, val = "score"))
d12_pc_sign <- c(calc_sign(d12g0_pc_stats, true_grn12, pc = TRUE, val = "score"),
                calc_sign(d12g2_pc_stats, true_grn12, pc = TRUE, val = "score"),
                calc_sign(d12g5_pc_stats, true_grn12, pc = TRUE, val = "score"))

d1_genie_sign <- c(calc_sign(d1g0_genie_stats, true_grn1, val = "score"),
                calc_sign(d1g2_genie_stats, true_grn1, val = "score"),
                calc_sign(d1g5_genie_stats, true_grn1, val = "score"),
                calc_sign(d1g10_genie_stats, true_grn1, val = "score"))
d4_genie_sign <- c(calc_sign(d4g0_genie_stats, true_grn4, val = "score"),
                calc_sign(d4g2_genie_stats, true_grn4, val = "score"),
                calc_sign(d4g5_genie_stats, true_grn4, val = "score"),
                calc_sign(d4g10_genie_stats, true_grn4, val = "score"))
d12_genie_sign <- c(calc_sign(d12g0_genie_stats, true_grn12, val = "score"),
                calc_sign(d12g2_genie_stats, true_grn12, val = "score"),
                calc_sign(d12g5_genie_stats, true_grn12, val = "score"),
                calc_sign(d12g10_genie_stats, true_grn12, val = "score"))
```

```{r}
d1_pc_tib <- list(calc_sign(d1g0_pc_stats, true_grn1, pc = TRUE, val = "tibble"),
                calc_sign(d1g2_pc_stats, true_grn1, pc = TRUE, val = "tibble"),
                calc_sign(d1g5_pc_stats, true_grn1, pc = TRUE, val = "tibble"),
                calc_sign(d1g10_pc_stats, true_grn1, pc = TRUE, val = "tibble"))
d4_pc_tib <- list(calc_sign(d4g0_pc_stats, true_grn4, pc = TRUE, val = "tibble"),
                calc_sign(d4g2_pc_stats, true_grn4, pc = TRUE, val = "tibble"),
                calc_sign(d4g5_pc_stats, true_grn4, pc = TRUE, val = "tibble"),
                calc_sign(d4g10_pc_stats, true_grn4, pc = TRUE, val = "tibble"))
d12_pc_tib <- list(calc_sign(d12g0_pc_stats, true_grn12, pc = TRUE, val = "tibble"),
                calc_sign(d12g2_pc_stats, true_grn12, pc = TRUE, val = "tibble"),
                calc_sign(d12g5_pc_stats, true_grn12, pc = TRUE, val = "tibble"))

d1_genie_tib <- list(calc_sign(d1g0_genie_stats, true_grn1, val = "tibble"),
                calc_sign(d1g2_genie_stats, true_grn1, val = "tibble"),
                calc_sign(d1g5_genie_stats, true_grn1, val = "tibble"),
                calc_sign(d1g10_genie_stats, true_grn1, val = "tibble"))
d4_genie_tib <- list(calc_sign(d4g0_genie_stats, true_grn4, val = "tibble"),
                calc_sign(d4g2_genie_stats, true_grn4, val = "tibble"),
                calc_sign(d4g5_genie_stats, true_grn4, val = "tibble"),
                calc_sign(d4g10_genie_stats, true_grn4, val = "tibble"))
d12_genie_tib <- list(calc_sign(d12g0_genie_stats, true_grn12, val = "tibble"),
                calc_sign(d12g2_genie_stats, true_grn12, val = "tibble"),
                calc_sign(d12g5_genie_stats, true_grn12, val = "tibble"),
                calc_sign(d12g10_genie_stats, true_grn12, val = "tibble"))
```

```{r}
d1_pc_graph <- list()
for (i in 1:length(d1_pc_tib)) {
  curr <- d1_pc_tib[[i]] %>%
    group_by(rank) %>%
    summarise(sign = sum(sign), count = sum(rank) / mean(rank)) %>%
    mutate(sign = cumsum(sign), count = cumsum(count)) %>%
    mutate(sign_acc = sign / count)
  d1_pc_graph[[i]] <- curr
}
d4_pc_graph <- list()
for (i in 1:length(d4_pc_tib)) {
  curr <- d4_pc_tib[[i]] %>%
    group_by(rank) %>%
    summarise(sign = sum(sign), count = sum(rank) / mean(rank)) %>%
    mutate(sign = cumsum(sign), count = cumsum(count)) %>%
    mutate(sign_acc = sign / count)
  d4_pc_graph[[i]] <- curr
}
d12_pc_graph <- list()
for (i in 1:length(d12_pc_tib)) {
  curr <- d12_pc_tib[[i]] %>%
    group_by(rank) %>%
    summarise(sign = sum(sign), count = sum(rank) / mean(rank)) %>%
    mutate(sign = cumsum(sign), count = cumsum(count)) %>%
    mutate(sign_acc = sign / count)
  d12_pc_graph[[i]] <- curr
}



d1_genie_graph <- list()
for (i in 1:length(d1_genie_tib)) {
  curr <- d1_genie_tib[[i]] %>%
    group_by(rank) %>%
    summarise(sign = sum(sign), count = sum(rank) / mean(rank)) %>%
    mutate(sign = cumsum(sign), count = cumsum(count)) %>%
    mutate(sign_acc = sign / count)
  d1_genie_graph[[i]] <- curr
}
d4_genie_graph <- list()
for (i in 1:length(d4_genie_tib)) {
  curr <- d4_genie_tib[[i]] %>%
    group_by(rank) %>%
    summarise(sign = sum(sign), count = sum(rank) / mean(rank)) %>%
    mutate(sign = cumsum(sign), count = cumsum(count)) %>%
    mutate(sign_acc = sign / count)
  d4_genie_graph[[i]] <- curr
}
d12_genie_graph <- list()
for (i in 1:length(d12_genie_tib)) {
  curr <- d12_genie_tib[[i]] %>%
    group_by(rank) %>%
    summarise(sign = sum(sign), count = sum(rank) / mean(rank)) %>%
    mutate(sign = cumsum(sign), count = cumsum(count)) %>%
    mutate(sign_acc = sign / count)
  d12_genie_graph[[i]] <- curr
}

ggplot(d1_pc_graph[[1]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("pc 100 60") +
  coord_cartesian(ylim=c(0, 1))
ggplot(d1_pc_graph[[2]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("pc 100 200") +
  coord_cartesian(ylim=c(0, 1))
ggplot(d1_pc_graph[[3]], aes(x = rank, y = sign_acc)) +
  geom_line() + 
  ggtitle("pc 100 500") +
  coord_cartesian(ylim=c(0, 1))
ggplot(d1_pc_graph[[4]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("pc 100 1000") +
  coord_cartesian(ylim=c(0, 1))

ggplot(d4_pc_graph[[1]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("pc 400 60") +
  coord_cartesian(ylim=c(0, 1))
ggplot(d4_pc_graph[[2]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("pc 400 200") +
  coord_cartesian(ylim=c(0, 1))
ggplot(d4_pc_graph[[3]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("pc 400 500") +
  coord_cartesian(ylim=c(0, 1))
ggplot(d4_pc_graph[[4]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("pc 400 1000") +
  coord_cartesian(ylim=c(0, 1))

ggplot(d12_pc_graph[[1]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("pc 1200 60") +
  coord_cartesian(ylim=c(0, 1))
ggplot(d12_pc_graph[[2]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("pc 1200 200") +
  coord_cartesian(ylim=c(0, 1))
ggplot(d12_pc_graph[[3]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("pc 1200 500") +
  coord_cartesian(ylim=c(0, 1))


ggplot(d1_genie_graph[[1]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("genie 100 60") +
  coord_cartesian(ylim=c(0, 1))
ggplot(d1_genie_graph[[2]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("genie 100 200") +
  coord_cartesian(ylim=c(0, 1))
ggplot(d1_genie_graph[[3]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("genie 100 500") +
  coord_cartesian(ylim=c(0, 1))
ggplot(d1_genie_graph[[4]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("genie 100 1000") +
  coord_cartesian(ylim=c(0, 1))

ggplot(d4_genie_graph[[1]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("genie 400 60") +
  coord_cartesian(ylim=c(0, 1))
ggplot(d4_genie_graph[[2]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("genie 400 200") +
  coord_cartesian(ylim=c(0, 1))
ggplot(d4_genie_graph[[3]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("genie 400 500") +
  coord_cartesian(ylim=c(0, 1))
ggplot(d4_genie_graph[[4]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("genie 400 1000") +
  coord_cartesian(ylim=c(0, 1))

ggplot(d12_genie_graph[[1]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("genie 1200 60") +
  coord_cartesian(ylim=c(0, 1))
ggplot(d12_genie_graph[[2]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("genie 1200 200") +
  coord_cartesian(ylim=c(0, 1))
ggplot(d12_genie_graph[[3]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("genie 1200 500") +
  coord_cartesian(ylim=c(0, 1))
ggplot(d12_genie_graph[[4]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("genie 1200 1000") +
  coord_cartesian(ylim=c(0, 1))

##gebruikte plot
ggplot(d4_pc_graph[[3]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("PC: 400g - 500 plants") +
  ylab("Sign accuracy") +
  coord_cartesian(ylim=c(0, 1))

ggplot(d4_genie_graph[[3]], aes(x = rank, y = sign_acc)) +
  geom_line() +
  ggtitle("GENIE3: 400g - 500 plants") +
  ylab("Sign accuracy") +
  coord_cartesian(ylim=c(0, 1))
```

```{r}
pc_sign <- calc_sign(d4g5_pc_stats, true_grn4, pc = TRUE, val = "tibble")
genie_sign <- calc_sign(d4g5_genie_stats, true_grn4, val = "tibble")

pc_sign <- pc_sign %>%
  group_by(rank) %>%
  summarise(sign = sum(sign), count = sum(rank) / mean(rank)) %>%
  mutate(sign = cumsum(sign), count = cumsum(count)) %>%
  mutate(sign_acc = sign / count) %>%
  mutate(method="pc")

genie_sign <- genie_sign %>%
  group_by(rank) %>%
  summarise(sign = sum(sign), count = sum(rank) / mean(rank)) %>%
  mutate(sign = cumsum(sign), count = cumsum(count)) %>%
  mutate(sign_acc = sign / count) %>%
  mutate(method="genie")

merged <- rbind(pc_sign, genie_sign)
merged$method <- factor(merged$method, levels=c("bc3net", "pc", "genie"))

ggplot(merged, aes(x=rank, y=sign_acc, color=method)) +
  geom_line() +
  ggtitle("400g - 500 plants") +
  ylab("Sign accuracy") +
  coord_cartesian(ylim=c(0, 1)) +
  scale_color_manual(values=c("#00BA38", "#619CFF"))

```


### plots
```{r}
grn4 <- mutate(true_grn4, sign = TRUE)

end_rank_genie <- nrow(filter(d4g10_genie_stats[[2]][[2]], count >= 50))
end_rank_pc <- nrow(filter(d4g10_pc_stats[[2]][[2]], count >= 50))

d4g10_pc_sign <- filter(d4g10_pc_stats[[2]][[1]], rank <= end_rank_pc) %>%
  # adjust TP's to only be true when sign is correct
  filter(directed==TRUE) %>%
  left_join(grn4, by = c('reg', 'target')) %>%
  mutate(sign = ifelse(is.na(sign), 1, 0)) %>%
  mutate(TP_new = ifelse((TP == 1 & sign == 1), 1, 0)) %>%
  group_by(rank) %>%
  summarise(TP = sum(TP_new), count = sum(rank) / mean(rank)) %>%
  mutate(cumTP = cumsum(TP), rec = (TP / count) / nrow(true_grn4)) %>%
  mutate(cumcount = cumsum(count), cumrec = cumsum(rec)) %>%
  mutate(cumprec = cumTP / cumcount) %>%
  mutate(F1 = (2*cumrec*cumprec)/(cumrec+cumprec)) %>%
  mutate(method = 'pc')

d4g10_genie_sign <- filter(d4g10_genie_stats[[2]][[1]], rank <= end_rank_genie) %>%
  # adjust TP's to only be true when sign is correct
  filter(directed==TRUE) %>%
  left_join(grn4, by = c('reg', 'target')) %>%
  mutate(sign = ifelse(is.na(sign), 0, 1)) %>%
  mutate(TP_new = ifelse((TP == 1 & sign == 1), 1, 0)) %>%
  group_by(rank) %>%
  summarise(TP = sum(TP_new), count = sum(rank) / mean(rank)) %>%
  mutate(cumTP = cumsum(TP), rec = (TP / count) / nrow(true_grn4)) %>%
  mutate(cumcount = cumsum(count), cumrec = cumsum(rec)) %>%
  mutate(cumprec = cumTP / cumcount) %>%
  mutate(F1 = (2*cumrec*cumprec)/(cumrec+cumprec)) %>%
  mutate(method = 'genie')

ggplot(d4g10_pc_sign, aes(x=cumrec, y=cumprec)) +
  geom_line()

ggplot(d4g10_genie_sign, aes(x=cumrec, y=cumprec)) + 
  geom_line()

merged <- rbind(d4g10_genie_sign, d4g10_pc_sign) 
merged$method <- factor(merged$method, levels=c("bc3net", "pc", "genie"))

minrec <- min(c(max(d4g10_genie_sign$cumrec), max(d4g10_pc_sign$cumrec)))
genie_auc_rank <- filter(d4g10_genie_sign, cumrec <= minrec)
pc_auc_rank <- filter(d4g10_pc_sign, cumrec <= minrec)

auc_4g <- c(calc_auc(genie_auc_rank), calc_auc(pc_auc_rank))
F1_4g <- rbind(arrange(genie_prc, desc(F1))[1,], arrange(bc3_prc, desc(F1))[1,], arrange(pc_prc, desc(F1))[1,])

ggplot(merged, aes(x=cumrec, y=cumprec, color=method)) +
  geom_line() +
  scale_color_manual(values=c("#00BA38", "#619CFF")) +
  ggtitle("400 Genes - 1000 Plants | Accounting for direction") +
  xlab("Recall") + ylab("Precision") + 
  geom_hline(yintercept=exp_precision4/2, linetype="dashed", color="red") +
  coord_cartesian(ylim=c(0, 0.5), xlim=c(0, 0.1)) 


```



## Similarity of results
```{r}
d1g5_pc_dis <- distinct(group_by(d1g5_pc_stats[[2]][[1]], rank), reg, target) %>%
  summarise(dis = sum(rank)/mean(rank))
d1g5_pc_dis <- left_join(d1g5_pc_stats[[2]][[2]], d1g5_pc_dis, by="rank") %>%
  mutate(dupe = 1 - dis/count) %>%
  select(rank, rank_precision_adj, count, method, dupe) %>%
  filter(count >= 50)

d1g10_pc_dis <- distinct(group_by(d1g10_pc_stats[[2]][[1]], rank), reg, target) %>%
  summarise(dis = sum(rank)/mean(rank))
d1g10_pc_dis <- left_join(d1g10_pc_stats[[2]][[2]], d1g10_pc_dis, by="rank") %>%
  mutate(dupe = 1 - dis/count) %>%
  select(rank, rank_precision_adj, count, method, dupe) %>%
  filter(count >= 50)

d1g10_genie_dis <- distinct(group_by(d1g10_genie_stats[[2]][[1]], rank), reg, target) %>%
  summarise(dis = sum(rank)/mean(rank))
d1g10_genie_dis <- left_join(d1g10_genie_stats[[2]][[2]], d1g10_genie_dis, by="rank") %>%
  mutate(dupe = 1 - dis/count) %>%
  select(rank, rank_precision_adj, count, method, dupe) %>%
  filter(count >= 50)

d1g10_bc3_dis <- distinct(group_by(d1g10_bc3_stats[[2]][[1]], rank), reg, target) %>%
  summarise(dis = sum(rank)/mean(rank))
d1g10_bc3_dis <- left_join(d1g10_bc3_stats[[2]][[2]], d1g10_bc3_dis, by="rank") %>%
  mutate(dupe = 1 - dis/count) %>%
  select(rank, rank_precision_adj, count, method, dupe) %>%
  filter(count >= 50)

ggplot(d1g5_pc_dis, aes(x=rank, y=rank_precision_adj)) +
  geom_smooth() + 
  geom_point()

ggplot(d1g10_pc_dis, aes(x=rank, y=dupe)) + 
  geom_smooth() +
  geom_point()

ggplot(d1g10_bc3_dis, aes(x=rank, y=dupe)) + 
  geom_smooth() +
  geom_point()

ggplot(d1g5_pc_dis, aes(x=rank_precision_adj, y=dupe)) +
  geom_smooth() +
  geom_point()



d4g5_pc_dis <- distinct(group_by(d4g5_pc_stats[[2]][[1]], rank), reg, target) %>%
  summarise(dis = sum(rank)/mean(rank))
d4g5_pc_dis <- left_join(d4g5_pc_stats[[2]][[2]], d4g5_pc_dis, by="rank") %>%
  mutate(dupe = 1 - dis/count) %>%
  select(rank, rank_precision_adj, count, dupe) %>%
  filter(count >= 50) %>%
  filter(rank <= 250)

d4g5_genie_dis <- distinct(group_by(d4g5_genie_stats[[2]][[1]], rank), reg, target) %>%
  summarise(dis = sum(rank)/mean(rank))
d4g5_genie_dis <- left_join(d4g5_genie_stats[[2]][[2]], d4g5_genie_dis, by="rank") %>%
  mutate(dupe = 1 - dis/count) %>%
  select(rank, rank_precision_adj, count, dupe) %>%
  filter(count >= 50) %>%
  filter(rank <= 250)

d4g5_bc3_dis <- distinct(group_by(d4g5_bc3_stats[[2]][[1]], rank), reg, target) %>%
  summarise(dis = sum(rank)/mean(rank))
d4g5_bc3_dis <- left_join(d4g5_bc3_stats[[2]][[2]], d4g5_bc3_dis, by="rank") %>%
  mutate(dupe = 1 - dis/count) %>%
  select(rank, rank_precision_adj, count, dupe) %>%
  filter(count >= 50) %>%
  filter(rank <= 250)

ggplot(d4g5_pc_dis, aes(x=rank, y=dupe)) +
  geom_smooth() +
  geom_point()
ggplot(d4g5_pc_dis, aes(x=rank, y=rank_precision_adj)) +
  geom_smooth() +
  geom_point()
ggplot(d4g5_genie_dis, aes(x=rank, y=dupe)) +
  geom_smooth() +
  geom_point()
ggplot(d4g5_genie_dis, aes(x=rank_precision_adj, y=dupe)) +
  geom_smooth() +
  geom_point()
ggplot(d4g5_bc3_dis, aes(x=rank, y=dupe)) +
  geom_smooth() +
  geom_point()
```













